### ISSUE TITLE
No Notification red color on multiple account

### ISSUE THREAD

**Issue by grand303** [amanharwara/altus#101]
It would be great if there was a red notification on each account tab if there was a new message.

Because it is very difficult to know which account has a new message, if we log in with several whatsApp accounts.

Thanks.
![red notif](https://user-images.githubusercontent.com/67847888/96850198-bd589280-1480-11eb-8f69-11be8f0b9159.jpg)
![example](https://user-images.githubusercontent.com/67847888/96850221-c3e70a00-1480-11eb-8402-95cedeaa95fc.jpg)

**Comment by amanharwara** [comment]
Implemented in [v3.18.0](https://github.com/amanharwara/altus/releases/tag/3.18.0)

**Comment by grand303** [comment]
Thanks Mate, Now in version 3.18.0 there is no red notification in taskbar / dock if there is an incoming message.

**Comment by wahidisna** [comment]
> 
> 
> Thanks Mate, Now in version 3.18.0 there is no red notification in taskbar / dock if there is an incoming message.

I get this issue too. Windows 10 10.0.19041.264

**Comment by amanharwara** [comment]
[v3.18.1](https://github.com/amanharwara/altus/releases/tag/3.18.1) should fix this.

**Comment by amanharwara** [comment]
Closing as this has been fixed & I've received no further replies from the OP.
