### ISSUE TITLE
Can't turn off spellcheck or make it multi-lingual.

### ISSUE THREAD

**Issue by MesQueMai** [amanharwara/altus#102]
There is no option to turn off spell check or select a second language. The spellchecker is set to Spanish, anything I type in English or Catalan has a wavy red line underneath it.

I've:
- added English and Catalan to Windows languages in Windows Settings.
- turned off the Windows spell checker.

Expected behaviour - 
1st option - multi-lingual spell check. Clicking on right mouse button allows you to select the language you're typing in.
2nd option - ability to turn off spell checker.

**Information:**
Windows 10
Altus ver 3.19.0

**Comment by amanharwara** [comment]
I've added a toggle for the spell-check in [v3.20.0](https://github.com/amanharwara/altus/releases/tag/3.20.0)

**Comment by MesQueMai** [comment]
Wonderful! Thank you. 

I've installed v.3.20.0 and the lines no longer appear. I can't find the toggle switch, although it doesn't matter to me as I'll keep it off anyway.

Thanks again!

**Comment by amanharwara** [comment]
The toggle can be found in the tab settings which can be opened by clicking the cog icon next to the name of the tab.

**Comment by amanharwara** [comment]
I'll close this issue now
