### ISSUE TITLE
Issue with links preview when writing message

### ISSUE THREAD

**Issue by maicol07** [amanharwara/altus#103]
**Describe the bug**  
See screenshot for the graphical issue.

When sending the message or when link preview is closed (close button can't be clicked) chat messages shifts behind the utility bar

**To Reproduce**  

1.  Write a message with a link
2.  Check the issue

**Expected behavior**  
Link preview should be visible and, when closed not 

**Screenshots**

![immagine](https://user-images.githubusercontent.com/9463142/99701068-44a32100-2a94-11eb-9a07-6205c272e2ed.png)

**Information:**

*   OS: Windows 10
*   Altus Version 3.20.1

**Comment by amanharwara** [comment]
[v3.21.0](https://github.com/amanharwara/altus/releases/tag/3.21.0) should fix this.

**Comment by amanharwara** [comment]
Closing as this is fixed already.

**Comment by maicol07** [comment]
@amanharwara this issue has come back in v4 (links and replies hidden by the utility bar)

**Comment by amanharwara** [comment]
Wow, I completely forgot to implement the correct behaviour for this in this version. 🤦‍♂️

**Comment by amanharwara** [comment]
Fixed in [v4.1.0](https://github.com/amanharwara/altus/releases/tag/4.1.0). Also, previously the utility bar would take a lot of time to re-adjust when replying, but that should happen instantly now.

**Comment by maicol07** [comment]
Yes, it is instant. Should be added also when link is closed or removed.
![yWtsHHJe2G](https://user-images.githubusercontent.com/9463142/111778665-4f8c8780-88b5-11eb-9c32-b031b75095fb.gif)

**Comment by amanharwara** [comment]
> Should be added also when link is closed or removed.

I don't understand what you mean by that.

**Comment by maicol07** [comment]
Check the GIF. The speed when link is added is different from the one when link is removed

**Comment by amanharwara** [comment]
Previously it waited for a few seconds when a link/reply was added to calculate the height of the reply/link panel, and I was able to find out a way to do that without waiting. But it doesn't wait when the link is removed anyway, so I don't know how I can speed it up further.

**Comment by maicol07** [comment]
Ok. Anyway, it's fine if it works well!

**Comment by amanharwara** [comment]
Yes. I'll close this issue then.
