### ISSUE TITLE
Please add documentation or release as standard app

### ISSUE THREAD

**Issue by Pitriss** [amanharwara/altus#104]
Hello,

Please could you add documentation about how to compile it as normal app? I would like to use your app on arm64 and appimages are no-go for me as they are possible security threats. I hope for some sane solution.

**Comment by amanharwara** [comment]
There isn't a single way to compile Altus as it's an Electron app and just like other Electron apps there are multiple ways of compiling Altus. You can use something like [electron-builder](https://www.electron.build/) or [electron-packager](https://github.com/electron/electron-packager). I personally use `electron-builder` for compiling the releases. You can check out the documentation for the one you choose to use.

For electron-builder, I think you can just do `electron-builder -l --arm64` (which will compile it for Linux on arm64 architecture)
