### ISSUE TITLE
Message ist covered by "Formatting" / "Quick replies" area

### ISSUE THREAD

**Issue by Katermerlin** [amanharwara/altus#106]
Message ist covered by "Formatting" / "Quick replies" area, message not totally viible

**To Reproduce**

**Expected behavior**
Bug Repair
[Part of message covered]

**Screenshots**
(https://user-images.githubusercontent.com/34886288/100343787-22535b00-2fe0-11eb-8452-aa86f59d8ed4.jpg)

**Information:**
 - OS: [e.g. Windows] Win10 (32)
 - Altus Version [3.16.0

**Additional context**
None

**Comment by amanharwara** [comment]
Scrolling down completely doesn't fix this? I forgot to make it auto-scroll, but on my machine just scrolling to the very bottom fixes this.

**Comment by amanharwara** [comment]
If that doesn't work, try using the latest version i.e. [v3.22.0](https://github.com/amanharwara/altus/releases/tag/3.22.0)

**Comment by amanharwara** [comment]
Closing as this is fixed in the latest version.
