### ISSUE TITLE
Altus on Big Sure M1 chip

### ISSUE THREAD

**Issue by Dano1979** [amanharwara/altus#112]
Hello, 

I'm trying to set-up altus on my Mac Book Pro (M1 chip). I use te latest version 3.23.0. The program is starting ok. When I'm trying to ad and setup a tab it won't work. Any ideas how to fix it? 

Thank you. 

Regards, 

Daan

**Comment by amanharwara** [comment]
Can you check & see if [v4.0-beta1](https://github.com/amanharwara/altus/releases/tag/4.0.0-beta1) works for you?

**Comment by Dano1979** [comment]
Hello, 

Yes it works for me on M1. Great en thank’s. 

Regards, 

Daan Oude Moleman
