### ISSUE TITLE
When a second screen is attached there are problems.

### ISSUE THREAD

**Issue by VoS-Erik** [amanharwara/altus#115]
When I connect it on my second screen on windows, altus is there. But when I disattach the second screen then altus is not visible. (even after reinstall). I can see it running in taskmanager, but not on my screen.

**Comment by amanharwara** [comment]
Can you check if this still happens on [the latest version](https://github.com/amanharwara/altus/releases/tag/4.0.0-beta3)?

**Comment by amanharwara** [comment]
Waiting for a response from the original poster. Will close this in a few days if I don't get one.

**Comment by amanharwara** [comment]
Closing since no response from the OP since more than 20 days...
