### ISSUE TITLE
Emoji on the wrong place

### ISSUE THREAD

**Issue by Katermerlin** [amanharwara/altus#117]
When I write a message and want to insert an emoji at the end it happens that the emoji is inserted in the beginning of the text block rather tan at the end where hte cursor was located last....
It seems to happen only if several lines were written.
"Don't submit message on Enter" is on.

**To Reproduce**
Write a text with several lines and try to insert an emoji after the last character (It seems not to happen always)

1.

**Expected behavior**
Emoji always on the current cursor

**Screenshots**
![Altus issue](https://user-images.githubusercontent.com/34886288/104087646-a5afcf80-5261-11eb-8cb0-454db451a23a.gif)

**Information:**
Altus: 3.24.0
Electron: 10.1.6
Chrome: 85.0.4183.121
V8: 8.5.210.26-electron.0
OS: Windows_NT ia32 10.0.18363

**Additional context**
None

**Comment by amanharwara** [comment]
Sorry for the late reply. This is happening to me even without the setting turned on, so it's probably a bug in WhatsApp Web itself.
