### ISSUE TITLE
Copy version info button not working

### ISSUE THREAD

**Issue by maicol07** [amanharwara/altus#121]
**Describe the bug**  
Copy version info button not working

**To Reproduce**  

1.  Open Altus
2.  Go to About --> About
3.  Click Copy Version Info
4.  Check clipboard with Win + V: clipboard: infos not copied

**Expected behavior**  
Version info should be copied

**Information:**  
Altus v4.0.0-beta2

Windows 10

**Comment by amanharwara** [comment]
Thanks for bringing this to my attention. This is fixed in the next release.
