### ISSUE TITLE
Uninstalled but maybe not (installation problem)

### ISSUE THREAD

**Issue by Minibus93** [amanharwara/altus#122]
I uninstalled Altus to update it, when I try to re-install it it says "there's already a profile for the user" even tho the folder it points out doesn't exist anymore (due to uninstalling before) and it interrupts my installation. 

INFOs:
Uninstalled Altus version: 3.22
Altus version I tried to re-install: 3.24
OS : Windows 10 Home 20h2 x64 bit

Additional context :
Altus doesn't appear in the remove programs list and seems to not be in the registry either

**Comment by amanharwara** [comment]
Did you set a custom location during the installation?

**Comment by Minibus93** [comment]
Yeah I did

**Comment by amanharwara** [comment]
Have you tried manually deleting that folder and then trying to install?

If that folder is already deleted, try deleting the `Altus` folder located in `%appdata%` and then re-installing.

**Comment by Minibus93** [comment]
The folder is already deleted and even the Altus' Folder in %appdata% is deleted, yet it won't reinstall :(

**Comment by amanharwara** [comment]
Can you send a screenshot of the error?

**Comment by Minibus93** [comment]
Well, this is becoming hilarious :o
I tried to re-install now to take a screenshot (my last try of restart was after checking the folders in both Programs and %appdata%, so less than 1 hour ago and it didn't end up successful), when I opened the installer it still somehow remembers that I had once installed Altus (saying there's already a profile for the user) but after choosing the install location (the same I used as before, I re-created that with the same name) clicking "install" it went all fine...weird

I guess I'll try to use Altus as usual for a few hours and if everything goes fine I'll close the issue thread! :D

Just for future reference, what do you suggest to update? First uninstall the older version and then install the new one, or just download the new one and install it without previously delete the old one?

Thanks for the fast replies btw and for the amazing Altus of course! <3

**Comment by amanharwara** [comment]
I'd suggest just download a new one and install it without uninstalling the previous.
