### ISSUE TITLE
Grey Screen on macOS

### ISSUE THREAD

**Issue by hartber** [amanharwara/altus#124]
Hello Altus team,

I tried to install the 4.0.0 version on my macbook pro (macOS Catalina 10.15.6) and just get a grey screen after starting the program. Am I missing some prerequisites or what else could have gone wrong?

Looking forward to your help and thanks in advance

Bernd
<img width="1007" alt="Bildschirmfoto 2021-02-04 um 08 47 23" src="https://user-images.githubusercontent.com/51863957/106861125-a2bfc780-66c5-11eb-8fc6-b2c2a8df7bf1.png">

**Comment by rebelcode-xr** [comment]
Same on Big Sur: Beta 3 was working, but not the Stable! 😢

**Comment by amanharwara** [comment]
I have updated the `.dmg` file in the 4.0.0 release. Can you try it and let me know?

**Comment by rebelcode-xr** [comment]
Now works, thanks! 😄

**Comment by amanharwara** [comment]
Waiting for a response from the original poster. Will close this in a few days if I don't get one.

**Comment by amanharwara** [comment]
Closing since this should be fixed already, and I haven't received any reply from the OP.
