### ISSUE TITLE
Check for updates not working

### ISSUE THREAD

**Issue by maicol07** [amanharwara/altus#126]
**Describe the bug**  
The check for updates action doesn't work. After clicking Yes, no message is displayed

**To Reproduce**  

1.  Go to About-->Check for updates
2.  Click Yes
3.  Infinite wait...

**Expected behavior**  
A "No new version was found" message

**Information:**  
Altus: 4.0.0  
Electron: 11.2.1  
Chrome: 87.0.4280.141  
V8: 8.7.220.31-electron.0  
OS: Windows\_NT x64 10.0.19042

**Comment by amanharwara** [comment]
Fixed in [v4.1.0](https://github.com/amanharwara/altus/releases/tag/4.1.0).

**Comment by maicol07** [comment]
Yes, it seems working. Closing...
