### ISSUE TITLE
Emojis cannot be inserted by using colon

### ISSUE THREAD

**Issue by CollinAlpert** [amanharwara/altus#127]
**Describe the bug**
When typing a colon and start typing a description of an emoji (e.g. :cry), the appropriate emoji used to show up and I could insert it. This behavior always worked in version 3.x and stopped working after I upgraded to 4.0.0.

**To Reproduce**

1. Type a colon followed by the desired emoji's description.

**Expected behavior**
The emoji pops up.

**Information:**
Version Info (Go to About > About and click "Copy Version Info"): 4.0.0

**Comment by amanharwara** [comment]
I haven't changed anything related to this, so I don't know why this is happening. I'm currently not able to use Windows so right now I don't have any way to debug this.

**Comment by amanharwara** [comment]
So, it could be something related to the z-index of the utility bar. I won't be able to fix this right now since I don't have access to a Windows machine. I think you can use `Win+.` to access the emoji panel on Windows, maybe try that to check if it works with the utility bar.

**Comment by CollinAlpert** [comment]
Unfortunately, I'm using Linux. I'm fine disabling the utility bar, though.

**Comment by amanharwara** [comment]
Can you see if [v4.1.0](https://github.com/amanharwara/altus/releases/tag/4.1.0) fixes this issue with the utility bar?

**Comment by CollinAlpert** [comment]
Yes, looks good. Thanks for fixing!
