### ISSUE TITLE
v4.1.0 has broken Altus

### ISSUE THREAD

**Issue by maicol07** [amanharwara/altus#134]
**Describe the bug**  
Almost anything works

**To Reproduce**  

1.  Update to v4.1.0

**Expected behavior**  
Working...

**Screenshots**

![](https://user-images.githubusercontent.com/9463142/111753864-a1beb000-8897-11eb-9d13-d6ac995bc889.png)

**Information:**

```
Altus: 4.1.0
Electron: 11.3.0
Chrome: 87.0.4280.141
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.21301
```

**Additional context**  
Tried a force reload from File menu but it's not working... Settings are not opening. Any other command except About commands doesn't work

**Comment by amanharwara** [comment]
It's a broken build, and I've taken down the release for now. What's happened is that it didn't package the actual code for the Altus UI before building the installers. I'll get it fixed in a bit. Please downgrade to 4.0.0. And sorry for the inconvenience.

**Comment by maicol07** [comment]
:+1: Waiting the new build

**Comment by amanharwara** [comment]
Can you download the `.exe` from https://github.com/amanharwara/altus/actions/runs/667741650 and see if it works? Don't mind the error there, the `.exe` build should be done correctly here.

**Comment by maicol07** [comment]
Works!

**Comment by amanharwara** [comment]
Cool. I'll upload that to the release. Closing this.
