### ISSUE TITLE
Title bar not in dark mode (windows standard)

### ISSUE THREAD

**Issue by tentaurus** [amanharwara/altus#138]
**Describe the bug**
The app title bar does not take over windows setting (dark mode). It's white!

**To Reproduce**

1.

**Expected behavior**
Title bat should be dark like all windows apps in dark mode.
v 3.24.0 fits well

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Information:**
4.1.0

**Additional context**

**Comment by amanharwara** [comment]
Closing this since this is basically the same as #125.

Btw, with [v4.2.0](https://github.com/amanharwara/altus/releases/tag/4.2.0) you can go to the Settings and enable "Custom Titlebar" which will bring back the v3.24.0-like titlebar.
