### ISSUE TITLE
Update available!

### ISSUE THREAD

**Issue by supertrio17** [amanharwara/altus#140]
Every time I open the app it says that update is available even tho I updated last time!

**Comment by amanharwara** [comment]
That is not an update for the app, that's something that WhatsApp Web keeps showing. Not sure what's causing that.

**Comment by supertrio17** [comment]
> That is not an update for the app, that's something that WhatsApp Web keeps showing. Not sure what's causing that.

I know, but is there any way to disable it or something?

**Comment by amanharwara** [comment]
> I know, but is there any way to disable it or something?

Unfortunately I haven't found any way to do so.

**Comment by iamvinny** [comment]
> > That is not an update for the app, that's something that WhatsApp Web keeps showing. Not sure what's causing that.
> 
> I know, but is there any way to disable it or something?

You can probably hide that with a custom css class

**Comment by amanharwara** [comment]
This shouldn't show up any more in [v4.3.0](https://github.com/amanharwara/altus/releases/tag/4.3.0).

**Comment by maicol07** [comment]
@amanharwara this issue is still there on first boot. Reloading the tab from the `File` menu allow us to get rid of it. However, it always show on first boot

**Comment by amanharwara** [comment]
> @amanharwara this issue is still there on first boot. Reloading the tab from the `File` menu allow us to get rid of it. However, it always show on first boot

That's weird. I've added code to detect it and remove it, maybe it isn't detecting it correctly.

**Comment by maicol07** [comment]
> > @amanharwara this issue is still there on first boot. Reloading the tab from the `File` menu allow us to get rid of it. However, it always show on first boot
> 
> That's weird. I've added code to detect it and remove it, maybe it isn't detecting it correctly.

Probably it is... Can you do something?

**Comment by amanharwara** [comment]
> Probably it is... Can you do something?

Are you using WhatsApp in a non-English language? Because the code checks for "Update available" which it might not find if you're using a non-English language.

**Comment by maicol07** [comment]
Yes, you're right. I'm using it in Italian

**Comment by amanharwara** [comment]
> Yes, you're right. I'm using it in Italian. Maybe there is an ID or class linked to the update available box

There is, and the code checks for that first. But the problem is, I'm not sure if there is any other notification of such sort which has the same class but might be actually important. Hence the code checks for the "Udpate available" string.

**Comment by maicol07** [comment]
@amanharwara if it can help this is the HTML markup of the "Update available" box:
```html
<div class="_2XcXo">
    <div class="_22XJC _1-SiY xx0PQ">
        <div class="_384go">
            <span data-testid="alert-update" data-icon="alert-update" class="">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" width="48" height="48">
                    <path fill="currentColor"
                        d="M24.154 2C11.919 2 2 11.924 2 24.165S11.919 46.33 24.154 46.33s22.154-9.924 22.154-22.165S36.389 2 24.154 2zm7.547 21.037h-6.738l3.08-3.08c-1.059-1.059-2.406-1.733-4.043-1.733-3.176 0-5.775 2.599-5.775 5.775 0 3.177 2.599 5.776 5.775 5.776 2.503 0 4.62-1.637 5.391-3.85h2.021c-.866 3.273-3.85 5.776-7.412 5.776-4.235 0-7.701-3.465-7.701-7.701 0-4.235 3.465-7.701 7.701-7.701 2.118 0 4.043.866 5.391 2.31l2.31-2.31v6.738z">
                    </path>
                </svg>
            </span>
        </div>
        <div class="_1Yy79">
            <div class="_2z7gr">Aggiornamento disponibile</div>
            <div class="_2BxMU">
                <span class="_3U3u1"><span class="_3jR9Y">Clicca per aggiornare WhatsApp</span>
                    <span data-testid="chevron-right-text" data-icon="chevron-right-text" class="gGn1n">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 8 12" width="8" height="12">
                            <path fill="currentColor"
                                d="M2.173 1l4.584 4.725-4.615 4.615-1.103-1.103 3.512-3.512L1 2.173 2.173 1z"></path>
                        </svg>
                    </span>
                </span>
            </div>
        </div>
    </div>
</div>
```
