### ISSUE TITLE
[Theme Manager] Update themes not working

### ISSUE THREAD

**Issue by John4266** [amanharwara/altus#142]
**Describe the bug**
A clear and concise description of what the bug is:
Everytime i click on "Update themes", the loading icon appears forever and nothing happens.
However, i do get an error in the Dev Tools Console.

**To Reproduce**

1. Go to Themes
2. Click on "Theme Manager"

**Expected behavior**
A clear and concise description of what you expected to happen:
it should update.

**Screenshots**
If applicable, add screenshots to help explain your problem:
![5zf3NNj](https://user-images.githubusercontent.com/70203256/113138716-06a0d100-91db-11eb-8ecd-b69ef799457b.png)

**Information:**
Version Info (Go to About > About and click "Copy Version Info"):
Altus: 4.2.0
Electron: 11.3.0
Chrome: 87.0.4280.141
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19043

**Additional context**
also the dark theme isn't even working at all for me.

**Comment by amanharwara** [comment]
It seems to be working on my machine. Not sure what is causing this.

**Comment by amanharwara** [comment]
Could you try going to `%appdata%/Altus` in Windows Explorer, then deleting the `themes.json` file and then trying again?

**Comment by John4266** [comment]
> 
> 
> Could you try going to `%appdata%/Altus` in Windows Explorer, then deleting the `themes.json` file and then trying again?

Just tried that, and seems like the error is not happening anymore.
However, i reinstalled the Dark Plus theme yet no theme is applying at all.

**Comment by John4266** [comment]
> 
> 
> > However, i reinstalled the Dark Plus theme yet no theme is applying at all.
> 
> Has the theme been selected for the tab after you deleted the file?

How exactly do i select it?
![image](https://user-images.githubusercontent.com/70203256/113142106-639e8600-91df-11eb-997b-69b416730760.png)

**Comment by John4266** [comment]
oh wait nvm i found it, and now it works.
ty!
