### ISSUE TITLE
Do you plan to work on a web site?

### ISSUE THREAD

**Issue by AnonymousWebHacker** [amanharwara/altus#145]
Is there future possibility of making the altus project like this? https://github.com/evgeny-nadymov/telegram-react
I mean that it can be hosted via web, not desktop

**Comment by amanharwara** [comment]
Something like that won't be possible until WhatsApp releases an API like there is with Telegram. Right now, it would probably require reverse engineering the WhatsApp code and that would probably lead to trouble with WhatsApp.
