### ISSUE TITLE
Altus Disregards Window Size

### ISSUE THREAD

**Issue by primewaydesign** [amanharwara/altus#146]
Everytime I start the app it disregards the window size I have setup in previous session.
The default window size is to small for my taste. So I always have to adjust the size manually.

Is there a way to fix this?

Other than that, excellent app. Thanks.

**Comment by amanharwara** [comment]
[v4.3.0](https://github.com/amanharwara/altus/releases/tag/4.3.0) has two settings that you can enable for this - "Remember Window Size" and "Remember Window Position"
