### ISSUE TITLE
 paste images from clipboard

### ISSUE THREAD

**Issue by cochayullo** [amanharwara/altus#149]
** Describe the error **
kubuntu 21.04, copy the images from the clipboard

**Play**
I open spectrable> I create a screen print -> I copy> but when pasting in the application it does not paste anything
good if everything else works

Is it something from my system or an unscheduled ability?

regards!

**Comment by amanharwara** [comment]
Working for me on Linux Mint 20.2 using either `Ctrl+V` or selecting `Paste` from the menu.
