### ISSUE TITLE
Pasting image from screenshot, makes two images attached

### ISSUE THREAD

**Issue by AleMarini** [amanharwara/altus#151]
Hello
I am a happy Altus user, thank a lot for your job!
On 4.3.0, I am facing an issue which I never had before (and I turned temporarily to 4.2.0).
Windows 10, Maxthon  browser (Version 6.1.2.2100 64 bit), I am using it as I always used, and I am using its built-in screenshot selector (png images, I think).
Since 4.3.0, whenever I take a screenshot and I paste it into Altus, it make me paste two images, identical.

I think this is a bug.

thanks a lot for your support.

![Cattura di Maxthon20210802110728](https://user-images.githubusercontent.com/88315887/127835471-3d6455c7-b38c-4a9e-ba5e-acbd2707556e.png)

**Comment by amanharwara** [comment]
Adding the "Help wanted" label since I don't use Windows and I this doesn't happen to me on Linux. Also, not sure if this is an Altus bug or a WhatsApp bug.

**Comment by AleMarini** [comment]
Altus 4.2.0 has not this effect
Altus 4.3.0 has this bug.
How can I help you? I am not a developer :(

**Comment by amanharwara** [comment]
Have you tried going back to 4.2.0 and checking if it really is a 4.3.0 issue only? Also, if possible, please test this in your browser as well. That might possibly help me narrow it down.

**Comment by AleMarini** [comment]
the bug is in 4.3.0 only. I re-installed 4.2.0 and it has not this bug (I'm using Altus since version 3.6/3.7 or something)
I'll re-install Altus 4.3.0 tonight, and give you a feedback. Thanks in the meanwhile

**Comment by amanharwara** [comment]
I reckon this might be an Electron issue since I haven't really changed anything else in 4.3.0 that would mess with the copy-paste.
Anyways, please try [v4.3.1](https://github.com/amanharwara/altus/releases/tag/4.3.1)

**Comment by AleMarini** [comment]
Thanks, but 
issue is the same :(

![image](https://user-images.githubusercontent.com/88315887/127870912-51f44efe-e425-4a4e-a101-38727b89c1c8.png)

**Comment by amanharwara** [comment]
That's weird. But I'm completely unsure as to what's causing this. In 4.3.0 I haven't changed anything related to copy-paste or images.

**Comment by amanharwara** [comment]
Does this issue still happen?

**Comment by AleMarini** [comment]
no, it was solved. Thanks :)

Il giorno ven 15 apr 2022 alle ore 19:24 Aman Harwara <
***@***.***> ha scritto:
