### ISSUE TITLE
grey / blank screen after update

### ISSUE THREAD

**Issue by chk1xn** [amanharwara/altus#154]
after updating my altus 3.x installation to 4.4.1 all tabs remain blank. forced reloads, closed tabs and created new ones, nothing worked. altus is connecting to the WA devices, showing the progress bar then turns all grey.
pc: Windows 10 Pro 21H1, WA: 2.21.16.20 on Android 4.4.2 and 10
I hope I'm not missing something obvious...

**Comment by amanharwara** [comment]
Have you tried deleting the `altus` or `Altus` folder in `%APPDATA%` and then re-trying?

**Comment by chk1xn** [comment]
FWIW, just installed v4.3.1 and everythings works like a charm...

**Comment by chk1xn** [comment]
> Have you tried deleting the `altus` or `Altus` folder in `%APPDATA%` and then re-trying?

Will try that later today. Will this wipe my customized themes?

**Comment by amanharwara** [comment]
Yes. Just copy the `themes.json` file to another place before deleting, and then you can paste it back.

**Comment by chk1xn** [comment]
after a complete uninstall and re-install 4.4.1 is working. thanks for the tip how to save my themes.
funny thing now if, once I turn on the option "prevent sending message on enter" and to hit ctrl-enter, I get this error:
![image](https://user-images.githubusercontent.com/5895303/130318417-fa505c20-99a2-4899-b4da-c91f72813c93.png)
