### ISSUE TITLE
ctrl-enter no longer works

### ISSUE THREAD

**Issue by chk1xn** [amanharwara/altus#155]
just updated from 3.24 to 4.4.1 and noticed once I turn on the option "prevent sending message on enter" and do hit ctrl-enter, I get this error:
![image](https://user-images.githubusercontent.com/5895303/130318644-5324b8ee-0be6-47d9-a7fa-f32dcf888560.png)
this used to work on the old/er version/s...

**Comment by amanharwara** [comment]
Fixed in [v4.4.2](https://github.com/amanharwara/altus/releases/tag/4.4.2)

**Comment by chk1xn** [comment]
thanks very much for this quick fix.
