### ISSUE TITLE
Whatsapp beta not working

### ISSUE THREAD

**Issue by Squar3wave** [amanharwara/altus#159]
Hello! Big fan of the Altus project. I'm using the AppImage version on MX Linux 19.4 (i use xfce, if this can be useful) and today i activated the beta version of whatsapp to use the service without having my phone connected to the internet. However this made so that Altus, after correctly connecting the first time, does not connect anymore. When restarting the app it just remains stuck on the loading screen, only to then end as displayed below. The service works fine while using it in normal whatsapp web on mozilla firefox. What can i do about it? Thanks in advance!

![image](https://user-images.githubusercontent.com/66468409/132861580-e174ffb2-1272-4b33-9ca9-340ede12e791.png)

**Comment by amanharwara** [comment]
That's not a language I understand. Can you translate it?

**Comment by Squar3wave** [comment]
Oh sorry! it just says "Connecting to Whatsapp, make sure that the computer is connected to the network" and in the green box "discconect"

**Comment by amanharwara** [comment]
Have you tried removing the tab and re-adding it?

**Comment by Squar3wave** [comment]
Removing the tab and logging in again scanning the qr code works, but it kind of defeats the purpose of using the beta service.

**Comment by akatarmo** [comment]
Same problem here. I have activated the new beta Whtasap's **multidevice** option and the symptoms are exactly the same as @Squar3wave described. In my case, I am using Altus on Windows 10 x64.

If I go back to the old system (not multidevice) everything works fine. Hope you can solve the problem soon. And **thank you very much** for sharing this nice piece of software.

**Comment by Minibus93** [comment]
Can reproduce. Same problem, It works when the phone is connected, but if it's disconnected then it doesn't

**Comment by alien2003** [comment]
Also can reprocude

**Comment by Afzxn** [comment]
same here. running ubuntu 20.4. 

it occurs everytime you re-launch altus.

**Comment by Fidelity88** [comment]
Same here! Both on Windows 10 and latstes MacOS

**Comment by amanharwara** [comment]
Finally got time today to work on this, and I think I've got it working locally 🤔 I'll push out a release, please then let me know whether it works or not.

**Comment by amanharwara** [comment]
Please test the Multi-device beta with this release and let me know: https://github.com/amanharwara/altus/releases/tag/4.5.3

Was working locally for me.

**Comment by Afzxn** [comment]
> Please test the Multi-device beta with this release and let me know: https://github.com/amanharwara/altus/releases/tag/4.5.3
> 
> Was working locally for me.

Working!

**Comment by akatarmo** [comment]
Yes, **working** for me too. Windows 10 x64. 

Thanks !!!

**Comment by Squar3wave** [comment]
Tried on Kubuntu 20.04, it works! Thanks a ton for your work @amanharwara !!

**Comment by amanharwara** [comment]
That's great to hear! I'll close this issue then. If there's any other issues related to this (but not exactly this), those should go in a new separate issue.
