### ISSUE TITLE
css in node_modules missing on port 5000

### ISSUE THREAD

**Issue by lackorol** [amanharwara/altus#160]
#### Description of problem
I wanted test electron app in chrome dev app with installed sveltie devtools.
My chrome version:
**Version 93.0.4577.63 (Official Build) (64-bit)**

#### Steps to reproduce
* run npm start
* go on localhost:5000

#### Expected behaviour
require (nodejs function) and css works in browser.

#### Screenshots ####
![Screenshot](https://user-images.githubusercontent.com/57800924/132881294-4857d277-6316-4b2f-ac82-fa1009cab955.png)

**Comment by amanharwara** [comment]
Altus can't work in Chrome, it requires Electron as it needs NodeJS functionality. Not a bug.
