### ISSUE TITLE
> Probably it is... Can you do something?

### ISSUE THREAD

**Issue by tentaurus** [amanharwara/altus#162]
> Probably it is... Can you do something?

Are you using WhatsApp in a non-English language? Because the code checks for "Update available" which it might not find if you're using a non-English language.

_Originally posted by @amanharwara in https://github.com/amanharwara/altus/issues/140#issuecomment-888907806_

**Comment by tentaurus** [comment]
Why not checking for more major languages? French, Spanish, German, ...
OR: can I do it by myselfe? Where? How?

**Comment by amanharwara** [comment]
Checking for every language is not possible. Also, I don't think this issue happens anymore...
