### ISSUE TITLE
PKGBUILD for Arch-based distributions

### ISSUE THREAD

**Issue by ngmoviedo** [amanharwara/altus#164]
I have created a simple PKGBUILD for better integration into Arch-based distributions. At the moment it just downloads and sets up the AppImage. I might try to program a version that compiles the source code using native dependencies, but I wasn't sure about the compilation process for Electron apps.

Here it is. Let me know what you think.
[altus-appimage-pkgbuild](https://github.com/ngmoviedo/altus-appimage-pkgbuild)

**Comment by amanharwara** [comment]
I'll try out this when I get time. I wasn't aware about that other pkgbuild either.

> but I wasn't sure about the compilation process for Electron apps.

The way you build Altus's AppImage would be something like this:
```
$ yarn
$ yarn build
```

This installs the dependencies, builds the frontend svelte code and then builds the final AppImage. 

If you wanted more control over either the svelte code compilation or electron compilation, you could do this:

```
$ yarn
$ yarn svelte-build
$ electron-builder
```

Of course you'd need yarn to be globally installed through `npm i -g` or `pacman`.

**Comment by amanharwara** [comment]
If `electron-builder` isn't installed globally, that will need to be `yarn electron-builder`
