### ISSUE TITLE
Reconnect after restart doesn't work anymore (iPhone)

### ISSUE THREAD

**Issue by tentaurus** [amanharwara/altus#170]
I connected my iPhone as usual. Works!
But when I restart altus is doesn't find the connection anymore...

Works well with Android.

**Comment by amanharwara** [comment]
Might be an issue with WhatsApp itself considering it's working with Android. Have you checked whether this issue also occurs on the browser (https://web.whatsapp.com) or not?

**Comment by tentaurus** [comment]
Funny, Today it works well again!
