### ISSUE TITLE
Could it be possible to center "Altus" title in custom tab bar?

### ISSUE THREAD

**Issue by Minibus93** [amanharwara/altus#171]
Hello,
first of all, thank you for mainteining this software that I really feel nice and well made!

Could it be possible to have the "Altus" name centered in the  Altus' custom tab bar?

![Immagine](https://user-images.githubusercontent.com/73554423/140641182-2c52e0f1-8db2-4223-8ece-96978c1d5013.png)

As you can see, the actual center should be where the red cross is, but Altus if a bit on right side.
By a quick looking I think "Altus" center itself without considering the options (File, edit, etc...) on the left and the window control on the right, but I could be wrong.

It's a really small detail so of course feel free to don't consider this because it actually doesn't really impact Altus' usage, but would be a pretty "aesthetic improvement"

**Comment by amanharwara** [comment]
https://github.com/amanharwara/altus/releases/tag/4.5.1

**Comment by Minibus93** [comment]
Wow, I wasn't expecting a so fast implementing! Thank you so much!

Just installed and can confirm it's perfectly centered!
