### ISSUE TITLE
After restart of Altus, the previous connection does not work anymore

### ISSUE THREAD

**Issue by TheBallarini** [amanharwara/altus#172]
After updating to the Version 4.0.0 Altus does not reconnect to the previous connection anymore. I need to reconnect to my WhatsApp Account via QR-Code scan every time I start Altus. Update to the latest version 4.5.1 did not help. The issue is the same.

**Comment by amanharwara** [comment]
Are you using the WhatsApp Beta?

**Comment by TheBallarini** [comment]
That I cannot say. On my Mac I'm using Version 2.2142.12
and on my iPhone Version 2.21.211.2

**Comment by amanharwara** [comment]
Was it working correctly before you updated Altus to 4.0? Can you remember what version you were on before?

**Comment by TheBallarini** [comment]
It was working like a charm before but unfortunately I did not pay attention to the version.
In my iPhone-WhatsApp I find all linked devices still active. I need to delete them manually.

**Comment by amanharwara** [comment]
Hmm that's odd. Can you try with a fresh install? What I mean by this is uninstall Altus, delete the `~/Library/Application Support/Altus` folder (**Make sure you only delete the Altus folder and not anything else, otherwise it might break other apps**) and then install Altus again.

**Comment by TheBallarini** [comment]
I deleted and reinstalled the Altus App and now I see in the Altus window that I'm running  WhatsApp Web BETA. It even tells me BETA next to my profile picture. How can I correct that?

**Comment by amanharwara** [comment]
Go to WhatsApp on your phone > Linked devices > Multi-device beta > Leave beta

**Comment by TheBallarini** [comment]
I just found out and did exactly that. Now everything is working perfectly.
Thanks for your very quick help and the hints.

**Comment by amanharwara** [comment]
You're welcome! 😃👍
