### ISSUE TITLE
Not working for me anymore...?

### ISSUE THREAD

**Issue by mamophoto** [amanharwara/altus#173]
i have the latest version installed: 4.5.1
altus always says me in a window: stelle sicher das dein computer eine aktive internetverbindung hat.
(and yes i have a connection) ;-)

mac os version: 11.6.1 big sur

disconnected from WhatsApp with all accounts and reconnected. 
still not working :-(

**Comment by amanharwara** [comment]
This is probably because you're using WhatsApp Multi-Device Beta. Go to WhatsApp on your phone, click on the menu > "Linked devices" > "Multi-device beta" and then click "Leave Beta"

**Comment by mamophoto** [comment]
OMG Sorry this is my fault, i thought this is necessary for the function to use WhatsApp without the phone.
thank you - and sorry again...

**Comment by amanharwara** [comment]
No need to apologize :)

> i thought this is necessary for the function to use WhatsApp without the phone.

If you want to be able to turn off your phone and still be able to use WhatsApp on the PC, the Beta is necessary, but unfortunately that means that it then stops working with Altus. I'm trying to find out how I can make it work, but I can't promise anything :)
