### ISSUE TITLE
4.5.1 failure on first start in Windows 11

### ISSUE THREAD

**Issue by michalfita** [amanharwara/altus#174]
**Describe the bug**
The following error appears in Windows 11 or first attempt to run:
![image](https://user-images.githubusercontent.com/4925040/141778215-07446cca-23b9-4a0d-8dde-d63bc3943514.png)

**To Reproduce**

1. Install for all users on Windows 11
2. Run

**Expected behavior**
No errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/4925040/141778215-07446cca-23b9-4a0d-8dde-d63bc3943514.png)

**Information:**
4.5.1

**Additional context**
Windows version:
![image](https://user-images.githubusercontent.com/4925040/141778672-76a5b9a0-6965-4dc6-bc11-9d34bf1b7bc2.png)

**Comment by amanharwara** [comment]
Oh right, on first that folder wouldn't have been created. Will push a fix soon.

**Comment by amanharwara** [comment]
https://github.com/amanharwara/altus/releases/tag/4.5.2 should fix this.

**Comment by michalfita** [comment]
Thanks, @amanharwara for fixing this so quickly. I don't have time to clean up and check if that really works in my case - sorry.
