### ISSUE TITLE
Help wanted: Fixing "Update Chrome" error break Multi-device beta, and vice-versa.

### ISSUE THREAD

**Issue by amanharwara** [amanharwara/altus#179]
Here is the reason why this happens:
https://github.com/amanharwara/altus/issues/178#issuecomment-988590207

> Right now, to fix the "Update Chrome" error, Altus unregisters the service workers, and clears the WebSQL db and the IndexedDB attached to WhatsApp. Admittedly, I'm not sure if clearing all of that is required. If somebody can isolate what we need to clear/unregister to fix the "Update Chrome" error, then it might be possible to only remove that, and keep what's necessary for the Multi-device beta to work.

Issues related to this:
- #178
- #159

**I've created this issue to hopefully get the notice of other developers who might be able to help me fix this, by doing what I've mentioned in the quote above.**

**Comment by Afzxn** [comment]
DO NOT CLICK "Update" on Whatsapp. The app stop working. 

this can easily be reversed by uninstalling the app completely (including config) and reinstalling.

**Comment by mamophoto** [comment]
hello everyone this is still not fixed?
i always get this message since the last update... :-(
<img width="742" alt="Screenshot 2022-02-02 um 09 24 44" src="https://user-images.githubusercontent.com/44875464/152119057-f36b54cc-68bd-4a8c-a5f0-3b25119ef553.png">

**Comment by Afz-Git** [comment]
> hello everyone this is still not fixed? i always get this message since the last update... :-( <img alt="Screenshot 2022-02-02 um 09 24 44" width="742" src="https://user-images.githubusercontent.com/44875464/152119057-f36b54cc-68bd-4a8c-a5f0-3b25119ef553.png">

It happens to me too time to time and for some random reason it goes back to being normal... try completely removing it or deleting the config maybe?

**Comment by mamophoto** [comment]
it works with Force Reload but with every new start of the app it goes back to the Screen above.

**Comment by mamophoto** [comment]
i already installed the app new a few times in the last month

**Comment by AfzGit** [comment]
Same here. The problem comes back frequently.

**Comment by mamophoto** [comment]
it dosnt work anymore for me... so i get back for my private account to the official WhatsApp app and use altus only for the business WhatsApp
that was not the idea... please fix this great app :-(

**Comment by mamophoto** [comment]
i think this is the actual reason: https://www.theverge.com/2022/3/11/22972381/whatsapp-meta-code-verify-web-browser-security-hash
