### ISSUE TITLE
Add contact/send message?

### ISSUE THREAD

**Issue by Dhanamerdeka** [amanharwara/altus#181]
can you add send messages button?
i mean... when we need to chat somone... we need to add them first on contact right?
but other method to get it done is use 
https://wa.me/<number here>
example https://wa.me/62812345689

can you add that feature? so instead opening chrome/browser to type that number
we can click chat button and insert the number. so will be store alot of effords and time?

maybe this is good idea

**Comment by amanharwara** [comment]
Isn't this the same as #157?

**Comment by Dhanamerdeka** [comment]
> Isn't this the same as #157?

Ah yeah sorry...
i swear i already search my previous suggestion. and that not found... i really sorry... i think it deleted or something
but it still open...
sorry, and thanks alot
i will close this... sorry :(
