### ISSUE TITLE
Altus 4.5.6 does not work and crashes

### ISSUE THREAD

**Issue by Johnnyy500** [amanharwara/altus#191]
**Describe the bug**
A clear and concise description of what the bug is:
When I open Altus, it quit immediately. Apple's problem report will open. When you press on "Reopen", Altus opens with a blank screen and does not respond. I have to force quit.

**To Reproduce**

1. Have Altus 4.0.0 installed on your Macbook.
2. Install Altus 4.5.6. and replace it for the altus 4.0.0.
3. Open Altus and allow in the security preferences.

**Expected behavior**
A clear and concise description of what you expected to happen:
It should work after installing and allowing it.

**Screenshots**
If applicable, add screenshots to help explain your problem:
<img width="997" alt="image" src="https://user-images.githubusercontent.com/60765771/158338622-faef0eb8-77ab-42ae-bf18-8cf412d505b1.png">
<img width="926" alt="image" src="https://user-images.githubusercontent.com/60765771/158338943-d4b0c3cd-63d1-4eb5-beed-c3d5aea31d84.png">

**Information:**
Version Info (Go to About > About and click "Copy Version Info"):
4.5.6.

**Additional context**

[Click here](https://www.codepile.net/pile/rylPrDyd) to see the apple problem report

**Comment by Johnnyy500** [comment]
Still got the problem. Tried to reinstall several times. Nobody can help? 😢

**Comment by amanharwara** [comment]
I think this is because you're using an M1-based Mac (Apple Silicon). For that use the dmg has an `arm64` prefix:
https://github.com/amanharwara/altus/releases/download/4.7.1/Altus-4.7.1-arm64.dmg

Let me know if whether this fixes it or not.

**Comment by Johnnyy500** [comment]
Thank you for your reply. I don't have the M1 based Mac. After updating to 4.7 it works! Thanks
