### ISSUE TITLE
Cool project. Can you port Altus to old sweet Win10Mobile?

### ISSUE THREAD

**Issue by mediaexplorer74** [amanharwara/altus#202]
Hi, [Amanharwara](https://github.com/amanharwara). 
Cool project.  Oh, my dream is to "recover" WebWhatsApp on my Lumia WinPhone (os: Windows 10 Mobile, min. os. build / SDK: 15063)...  =)))
Can you port Altus to old sweet Win10Mobile?
But idk Electron supports W10M or not... Maybe, Apache Cordova is more userful...

Best,
mediaexplorer74

**Comment by amanharwara** [comment]
Hi, Electron doesn't support W10M. Not sure about Cordova, but that would be out of the scope of this project anyways. I don't own a W10M device, and I can't really spend any time & resources on re-implementing Altus in Cordova. Hope you understand :)
