### ISSUE TITLE
Altus dosn't start on startup

### ISSUE THREAD

**Issue by ELXShadow** [amanharwara/altus#203]
**Describe the bug**
Altus dosn't start on startup since the new update

**To Reproduce**
1. Update to newest version
2. Restart PC

**Expected behavior**
It should start on startup like the previous update

**Information:**
Altus: 4.7.3
  Electron: 19.0.10
  Chrome: 102.0.5005.167
  V8: 10.2.154.15-electron.0
  OS: Windows_NT x64 10.0.22621

**Comment by ELXShadow** [comment]
By update I mean Altus update not Windows update

**Comment by ELXShadow** [comment]
Didint mean to complete it

**Comment by pythys** [comment]
I think this is a duplicate of #201 where essentially it stays stuck at connecting

**Comment by ELXShadow** [comment]
No this isn't what I meant, I fixed it by doing a clean install of Win11, but Altus just wouldn't start, not even in the tray or anything, even when I put Altus in the startup folder
