### ISSUE TITLE
Can't install, can't open on Mac :-(

### ISSUE THREAD

**Issue by mamophoto** [amanharwara/altus#205]
Can't install and can't open the newest Version on my Mac...
<img width="832" alt="Screenshot 2022-08-23 um 09 16 10" src="https://user-images.githubusercontent.com/44875464/186095532-9e0553fa-83b3-403f-baa1-d7fc6a064057.png">

**Comment by mamophoto** [comment]
27" i9 from 2019!

**Comment by amanharwara** [comment]
You have downloaded the Apple Silicon version (arm64). You need to download the regular dmg: https://github.com/amanharwara/altus/releases/download/4.7.4/Altus-4.7.4.dmg

**Comment by mamophoto** [comment]
hello and thank you! you should add this version to the website or both versions!
its not written on the main site: https://amanharwara.com/altus#downloads 
so i think you need one more button for the intel mac version.

**Comment by amanharwara** [comment]
Oh didn't realize that one downloads the arm version by default. Thanks for letting me know!

**Comment by mamophoto** [comment]
jep ;-) that’s the problem and also its not written on the website that 2 version exists :-)
