### ISSUE TITLE
Add call option

### ISSUE THREAD

**Issue by zafaraabis** [amanharwara/altus#212]

**Comment by zafaraabis** [comment]
In recent whatsapp app updates, you are able to call/video call on your client.
![image](https://user-images.githubusercontent.com/75385660/207395970-1f876c89-5fde-4ded-9f37-65546da823e5.png)
Keep up the good work :D

**Comment by amanharwara** [comment]
This is not something that I can control. Altus is only a wrapper for WhatsApp Web. So I can't implement this myself.
