### ISSUE TITLE
hi,can I pay some fees for you to complete some work on Altus?

### ISSUE THREAD

**Issue by jimenggirl** [amanharwara/altus#215]
hello,I would like you to add a few features
1: Configure a separate socks5/https proxy for each account
2: Access to google translate's API to translate messages in real time.

I will pay a fee for this, if you want, please send me your Telegram account

**Comment by amanharwara** [comment]
I'd recommend using a platform like [IssueHunt](https://issuehunt.io/) or [BountySource](https://bountysource.com/) if you want to pay someone to get this implemented. I'd be willing to accept PRs. But it's not something I'm going to implement at the moment.
