### ISSUE TITLE
Feature: Add new number to chat

### ISSUE THREAD

**Issue by Ghosty01** [amanharwara/altus#225]
Hey, on Web Whatsapp its possible to write to an new (not saved) number.

Just use the URL: [https://wa.me/{new_number}](https://wa.me/%7Bnew_number%7D).

Maybe you want to add this feauture.

**Comment by amanharwara** [comment]
[v4.8.5](https://github.com/amanharwara/altus/releases/tag/4.8.5) adds a "Start New Chat" option in the Files menu for this :)

**Comment by Ghosty01** [comment]
Much love <3
