### ISSUE TITLE
Scroll bar too small since 4.x 

### ISSUE THREAD

**Issue by imsa8800** [amanharwara/altus#232]
In Version 3.x when you open many tabs the scrollbar looks like that:

![grafik](https://user-images.githubusercontent.com/126565769/222153492-6f1782b9-bad5-423b-85a0-bfcf9afb75a0.png)

In Version 4.x when you open many tabs the scrollbar looks like that:

![grafik](https://user-images.githubusercontent.com/126565769/222153876-8cd800e9-b6e0-41c1-ba47-0ea0cb048bd1.png)

It is so small that you have to aim so exactly with the mouseand the contrast is bad. 
It is nearyl unusable.

**Comment by amanharwara** [comment]
Added a setting "Use system scrollbars" that will allow you to use the default Windows scrollbars (https://github.com/amanharwara/altus/releases/tag/4.8.4)

**Comment by imsa8800** [comment]
I can confirm that this is no working, and scrollbars look like in the 3.x Verison when setting is enabled.
many thanks
