### ISSUE TITLE
Altus 4.8.5 Theming issues

### ISSUE THREAD

**Issue by Squar3wave** [amanharwara/altus#233]
On version 4.8.5 Altus keeps on reverting to light theme and refuses to change theme when a different one is chosen from  the Edit Tab option. This has been observed on the .AppImage on both Ubuntu 22.04.2 and on the latest version of Arch Linux.

1. Open the tab dropdown menu
2. Click on "edit active tab"
3. Selecting a theme (In my case both Dark Plus and normal Dark didn't work)
4. Clicking on save reverts the settings to default theme

In order to change theme i had to open an old Altus version (either 4.8.1 or 4.8.3, depending on the machine i was working at the moment) and edit the tab there, the closing and reopening 4.8.5.
Even doing so, the Dark Plus theme sometimes results bugged, as some areas retain the light theme (i.e. the search box and the text box when sending images). However this beaviour is not consistent.

Thank you as always for your great work!

**Comment by amanharwara** [comment]
Fixed in [v4.8.6](https://github.com/amanharwara/altus/releases/tag/4.8.6)
