### ISSUE TITLE
[Enhancement] Language Translation

### ISSUE THREAD

**Issue by cdmichaelb** [amanharwara/altus#239]
chatgpt is a good one, but really any translation source, require us to supply api/access key.

Perhaps browser plugin support would be enough of a fix for this?

Edit: Sorry I seem to be unable to apply labels.

**Comment by amanharwara** [comment]
Browser plugin support is not something I intend to implement and maintain. If that is a necessity for you and you can implement it yourself, I would recommend forking Altus.
