### ISSUE TITLE
Feature Request - Support Flatpak/Snap

### ISSUE THREAD

**Issue by dtantono** [amanharwara/altus#244]
Hi
To support multiple distributions and Flatpak/snap is good to foster streamlined update for Linux. Is this possible to support Flatpak/snap?

**Comment by amanharwara** [comment]
To be honest, I'm not really interested in maintaining any more distributions, especially ones that I don't use myself. If someone wants to create a third-party distribution on Flathub or the Snap store, or create a PR that automates it so that I don't have to maintain it, then I'll accept it
