### ISSUE TITLE
Spell check doesn't work anymore...

### ISSUE THREAD

**Issue by Katermerlin** [amanharwara/altus#252]
I enjoyed using the spell check in Altus (German), wrong written words were underlined red.
But since a couple of weeks it doesn't work anymore and I don't know why...

Where can I switch this feature off and on?
Is it a built-in feature of Altus?
Or ist it a feature or Windows (10-32 pro)?
Or a feature of the browser? (I'm using Firefox portable)

I already tinkered with the Win-Adjustments but it didn't really work...

Does anybody know whatdo do...?

Thanks a lot for hints,

Wolfgang

**Comment by amanharwara** [comment]
Did this happen after you update or did it randomly happen?

**Comment by Katermerlin** [comment]
Back from holidays... 😊

I cannot tell you exactly from when it is. Anyways, the function with the red underlined spell 
checks don't work in 4.8.6 ...

It's not randomly, it's permanently...

Should I try a previous version?

At the moment it seems that only the Win10 spell check is working which I don't like, it gives 
always several proposals which disturbs me at writing. I'll be switching that off.

Regards
Wolfgang

Am 15.08.2023 um 18:55 schrieb Aman Harwara:
> Did this happen after you update or did it randomly happen?
> 

-- 
Diese E-Mail wurde von Avast-Antivirussoftware auf Viren geprüft.
www.avast.com

**Comment by Katermerlin** [comment]
Can it be that there used to be an item "Spelling" on / off  in the settings in a former version...?
I think I remember to tomething like that... anyways, at the moment I don't find a setting for this...
How does the spelling work in Altus...? Does it use settings of the browser or windows? Which source / dictionary does it use to compare the spelling?

**Comment by amanharwara** [comment]
> Can it be that there used to be an item "Spelling" on / off in the settings in a former version...?

There is a setting called "Spellcheck" for each tab, if you click the settings icon next to the tab name. If that's not enabled, enable it and then close and re-open Altus.

**Comment by Katermerlin** [comment]
OK, that was it... For some reason the switch was set "Off", no idea why...
Which dictionary does Altus use?

Anyways, thanks a lot for your help!!!
Regards
Wolfgang

**Comment by amanharwara** [comment]
> OK, that was it... For some reason the switch was set "Off", no idea why

I think it's set to off by default on new tabs. Maybe it makes more sense for it to be on by default

> Which dictionary does Altus use?

Altus is based on the [Electron](https://www.electronjs.org/docs/latest/tutorial/spellchecker) framework, which uses [Hunspell](https://hunspell.github.io/)
