### ISSUE TITLE
Cannot Open on M1 Macbook

### ISSUE THREAD

**Issue by albertoeficore** [amanharwara/altus#260]
A clear and concise description of what the bug is:
Cannot get this to install on a M1 Apple Macbook

**To Reproduce**

1. Try to install, dragging the Altus icon to the Apps folder as prompted by iOS, a shortcut appears on the desktop

**Expected behavior**
A clear and concise description of what you expected to happen:
After APP was installed, open it successfully

**Screenshots**
I have attached screenshots showing system info, app info and the error that appears

**Information:**
Version Info: 4.8.6
A screenshot was attached

**Additional context**
The regular x86 version was inadvertently installed, but was removed before attempting to install ARM version

![Screenshot 2023-10-30 102823](https://github.com/amanharwara/altus/assets/149377726/f6b3b9e3-f300-4b77-b88e-9f3d4088c032)
![ece163f7-8e48-4731-8877-427de5112b4a](https://github.com/amanharwara/altus/assets/149377726/f59bcf1b-a56d-459d-bced-12dc70680547)
![Screenshot 2023-10-30 102721](https://github.com/amanharwara/altus/assets/149377726/05847679-55ea-4cda-be45-019f49dfa3a4)

**Comment by amanharwara** [comment]
Running this command in the terminal should fix it:

```
xattr -d com.apple.quarantine /Applications/Altus.app
```

see: https://apple.stackexchange.com/questions/372084/macos-catalina-app-is-damaged-and-cant-be-opened-you-should-move-it-to-the-t/372208#372208

**Comment by albertoeficore** [comment]
That did not work. Here is the attached screenshot with the Terminal error message: "no such xattr"

However after digging around I tried the following command:

sudo xattr -dr com.apple.quarantine /Applications/Altus.app

And this time it worked!
![Screenshot 2023-10-31 174453](https://github.com/amanharwara/altus/assets/149377726/62fcad7c-37e9-4c06-baf4-1d750d47df02)

Thanks for your help pointing me in the right direction!

Altus is a killer app
