### ISSUE TITLE
WA in small strip in middle of Altus window

### ISSUE THREAD

**Issue by Tim09122** [amanharwara/altus#264]
**Describe the bug**
New laptop so downloaded Altus and connected WA account to new tab.

WA appears in thin vertical strip in middle of Altus window and is so small to be unreadable.

**To Reproduce**

As above. Uninstalled Altus and retried with same result.

**Expected behavior**
On previous laptop WA fills the Altus window. I expected it to be the same.

**Screenshots**
![IMG_20231227_195605861](https://github.com/amanharwara/altus/assets/155018033/221f4d6b-4b0a-49bd-a073-834a08a3f54f)

**Information:**
Altus: 4.8.6
  Electron: 22.0.1
  Chrome: 108.0.5359.125
  V8: 10.8.168.22-electron.0
  OS: Windows_NT x64 10.0.22631

**Additional context**
New laptop is Windows 11 Home 22631.2861
Screen resolution is 2560 x 1600 (may be relevant).

**Comment by amanharwara** [comment]
Have you maybe zoomed out too much?

**Comment by Tim09122** [comment]
Hi,

No, there is no zoom. It just comes up like that when I launch it.

Tim


------ Original Message ------
From "Aman Harwara" ***@***.******@***.***>>
To "amanharwara/altus" ***@***.******@***.***>>
Cc "Tim09122" ***@***.******@***.***>>; "Author" ***@***.******@***.***>>
Date Thu-28-12-2023 12:50:45
Subject Re: [amanharwara/altus] WA in small strip in middle of Altus window (Issue #264)

Have you maybe zoomed out too much? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: <="" div="">
DuckDuckGo removed one tracker. More<https://duckduckgo.com/-r-0TTDp6KtpGjvNd8tIABi1Qgkeqp-eVKX1zB5kJg1PXvl907Aopws_dQjS6rAvmVWgQOaUybVjHSAAEu-MdcX3-u1g1zM56Dm_lP1ga4Cz8hJULmfE6gzIn1oK_556jxfxPrscwXMOlx_rjdH9nmA9DIdXd2Q72ubWexGMohwUfjJdEeaQE3yIbEaYUxJoUtjULhvx_Ew4GM7Hoa7zmHC-jSchifzKcTd2otHOC_XcT5k7k9RrMZXXrQI5sw6pZ7HJrwOlyiU4m-OuL9vixi98VWGuye0LWZ9h8fAz86O-7hsTPP8lNvn4v-4-iGjLslekJE0u4en2Hqdd-HreCvUj2uwhDSCGZ5lz2g6BJ1-6jewfxSTy_vkwzIBVP7Aw>
Report Spam <https://duckduckgo.com/-r-0TTDp6KtpGjvNd8tIABi1Qgkeqp-eVKX1zB5kJg1PXvl907Aopws_dQjS6rAvmVWgQOaUybVjHSAAEu-MdcX3-u1g1zM56Dm_lP1ga4Cz8hJULmfE6gzIn1oK_556jxfxPrscwXMOlx_rjdH9nmA9DIdXd2Q72ubWexGMohwUfjJdEeaQE3yIbEaYUxJoUtjULhvx_Ew4GM7Hoa7zmHC-jSchifzKcTd2otHOC_XcT5k7k9RrMZXXrQI5sw6pZ7HJrwOlyiU4m-OuL9vixi98VWGuye0LWZ9h8fAz86O-7hsTPP8lNvn4v-4-iGjLslekJE0u4en2Hqdd-HreCvUj2uwhDSCGZ5lz2g6BJ1-6jewfxSTy_vkwzIBVP7Aw>

Have you maybe zoomed out too much?

**Comment by amanharwara** [comment]
What happens if you go to the View menu and press "Actual Size"?

**Comment by Tim09122** [comment]
There isn't an "actual size" option. Only toggle fullscreen:

***@***.***


------ Original Message ------
From "Aman Harwara" ***@***.******@***.***>>
To "amanharwara/altus" ***@***.******@***.***>>
Cc "Tim09122" ***@***.******@***.***>>; "Author" ***@***.******@***.***>>
Date Thu-28-12-2023 12:57:53
Subject Re: [amanharwara/altus] WA in small strip in middle of Altus window (Issue #264)

What happens if you go to the View menu and press "Actual Size"? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: <="" div="">
DuckDuckGo removed one tracker. More<https://duckduckgo.com/-rpEFovOsG3rOx79tOnw72-KZtZ5KmMsGovCnrWxCLMN9OM4DjCoqeugg4NJF6xI4B7dtL8ktphfiGPjmi3Xt9V9omkPT0WS23qv-WADAYcqUEh1bX658jtX2hZCYOyG98vuHUE34ejeuRpdVQXylVp8dAin8CwzBHcLdrH88nfZ3vh7kcfz4ug1_3Tf32iKliEEQt73MjB5WMh4Xr93mv9TEMuVnwMiy_0PTVso-j6GQbVZ0oauNSbS5oecThA1XpK2ExvYUDadOKswzmRqy1ah8n8BPL1TRnE9jffM6ZPGZeRlvJlPJ-7UWjio_3gR50_m9hjMZmzr0VtiI4LdSo-giaDDkjq06Ksj369rYu3eiP6RoLhQ3c5lBH2ryf39-u3lhF23V6rzj6MjGJclekIEaXKPz5F6jD-8IP9T6AuhS-hB4GHae0DRgN2je2vzSz29vE8yIBds7Q8>
Report Spam <https://duckduckgo.com/-rpEFovOsG3rOx79tOnw72-KZtZ5KmMsGovCnrWxCLMN9OM4DjCoqeugg4NJF6xI4B7dtL8ktphfiGPjmi3Xt9V9omkPT0WS23qv-WADAYcqUEh1bX658jtX2hZCYOyG98vuHUE34ejeuRpdVQXylVp8dAin8CwzBHcLdrH88nfZ3vh7kcfz4ug1_3Tf32iKliEEQt73MjB5WMh4Xr93mv9TEMuVnwMiy_0PTVso-j6GQbVZ0oauNSbS5oecThA1XpK2ExvYUDadOKswzmRqy1ah8n8BPL1TRnE9jffM6ZPGZeRlvJlPJ-7UWjio_3gR50_m9hjMZmzr0VtiI4LdSo-giaDDkjq06Ksj369rYu3eiP6RoLhQ3c5lBH2ryf39-u3lhF23V6rzj6MjGJclekIEaXKPz5F6jD-8IP9T6AuhS-hB4GHae0DRgN2je2vzSz29vE8yIBds7Q8>

What happens if you go to the View menu and press "Actual Size"?

**Comment by amanharwara** [comment]
Sorry, try this other method. Click inside WA somewhere to make sure focus is in there. Then press `Ctrl+0` (zero) on your keyboard and see if something happens.

**Comment by Tim09122** [comment]
Excellent! Solved the problem!

Thank you so much for your help.

Tim


------ Original Message ------
From "Aman Harwara" ***@***.******@***.***>>
To "amanharwara/altus" ***@***.******@***.***>>
Cc "Tim09122" ***@***.******@***.***>>; "Author" ***@***.******@***.***>>
Date Thu-28-12-2023 13:06:11
Subject Re: [amanharwara/altus] WA in small strip in middle of Altus window (Issue #264)

Sorry, try this other method. Click inside WA somewhere to make sure focus is in there. Then press Ctrl+0 (zero) on your keyboard and see if something happens. —Reply to this email directly, view it o
DuckDuckGo removed one tracker. More<https://duckduckgo.com/-rpEFovO1bZSJ7TzZgosdsIz_Sdvic5s51N5e3_KAmrWj0WY_SAtTaTAgrI8BaWhifcyub3QCb8UNptfyMTaNVuub6v7xNMJniolt_Ve89ECAhFdYFHq0vxy5XdTaaylAOzm98vuHUGbcHDvVM1uqwZ5Sy0Cn2kvq3OEHkCutIanpPbbxgjZMAfx2bk5_2RtmL3wZ6ZECMB4JmVOHDd9zQd7jd-b2BYLvBOTLcKH1_4jJ4w5V9L6xvqsrZ0Xb2RHTguUjZekvacFbEhMC-cOU0KmLVeh9H8BPN1IUFxP4z1zulNcXi7jzXw6cafWwoH-w0HIn8ztMZrNeOvR9comjNK_R_BE1mFJDif66pj367ao3Tcb3CPvDm-t7oKWi_u2Pj2HYSHnPGr3ueg_jg5gnJboCRGk0T2_Qup5z8HvR6_tWJ_apt0WBIiX7AFHC-we3VuZX-rp5X2yAR4ItT8>
Report Spam <https://duckduckgo.com/-rpEFovO1bZSJ7TzZgosdsIz_Sdvic5s51N5e3_KAmrWj0WY_SAtTaTAgrI8BaWhifcyub3QCb8UNptfyMTaNVuub6v7xNMJniolt_Ve89ECAhFdYFHq0vxy5XdTaaylAOzm98vuHUGbcHDvVM1uqwZ5Sy0Cn2kvq3OEHkCutIanpPbbxgjZMAfx2bk5_2RtmL3wZ6ZECMB4JmVOHDd9zQd7jd-b2BYLvBOTLcKH1_4jJ4w5V9L6xvqsrZ0Xb2RHTguUjZekvacFbEhMC-cOU0KmLVeh9H8BPN1IUFxP4z1zulNcXi7jzXw6cafWwoH-w0HIn8ztMZrNeOvR9comjNK_R_BE1mFJDif66pj367ao3Tcb3CPvDm-t7oKWi_u2Pj2HYSHnPGr3ueg_jg5gnJboCRGk0T2_Qup5z8HvR6_tWJ_apt0WBIiX7AFHC-we3VuZX-rp5X2yAR4ItT8>

Sorry, try this other method. Click inside WA somewhere to make sure focus is in there. Then press Ctrl+0 (zero) on your keyboard and see if something happens.

**Comment by amanharwara** [comment]
Awesome! Looks like it was zoomed in indeed. `Ctrl+0` should help you reset the zoom in case you zoom in by mistake.
