### ISSUE TITLE
Windows Security reporting trojan virus on Altus v5

### ISSUE THREAD

**Issue by cobrabr** [amanharwara/altus#273]
**Describe the bug**
Altus v5's executable is being reported as a trojan (`Trojan:Script/Wacatac.B!ml`) by Windows Security.

**To Reproduce**

1. Install Altus v5.
2. Run it.

**Screenshots**
![image](https://github.com/amanharwara/altus/assets/724969/3e94f0c1-ebac-4053-b423-ffa9c12404e9)

**Information:**
Version Info (Go to About > About and click "Copy Version Info"): Can't open it, since Windows quarantines the executable.

**Comment by cobrabr** [comment]
Any news on this?

**Comment by amanharwara** [comment]
This is most likely a false positive. The release is automatically built and uploaded using CI.
If you look at the VirusTotal result for this, nothing shows up https://www.virustotal.com/gui/file/53cba1eb694a591855435b575b29eda24f1a3e2c45d3664dd39065a178bb7e5c

![image](https://github.com/amanharwara/altus/assets/8348101/85b8cd98-130a-404f-ba26-a7553ef6200d)

**Comment by cobrabr** [comment]
Right, but that's the setup EXE, not the actual app EXE. Scanning the actual `Altus.exe` file on VirusTotal **does** show a virus: https://www.virustotal.com/gui/file/00ea166dddce35d8235464c7719fc40bccc6abbc8960577599833305bdf2bb38

![image](https://github.com/amanharwara/altus/assets/724969/fd732c84-af7f-4a40-8f10-afdf86fc86eb)

**Comment by amanharwara** [comment]
Your concern is totally understandable, 1 out of 63 seems like it's probably a false positive. If that is too much of a risk for your threat model, consider running it directly from the source by cloning the repo locally and compiling it yourself. I try to make sure, to the best of my ability, that any sort of dependency I use is actually safe.
