### ISSUE TITLE
Application Cant To Quit / Close / Exit On MacOS Monterey

### ISSUE THREAD

**Issue by alsyundawy** [amanharwara/altus#274]
Application Cant To Quit / Close / Exit On MacOS Monterey

for now just using force quit -_-

**Comment by Lnunovero92** [comment]
I take advantage of this publication of the colleague, to report that the same problem occurs for Windows users.

**Comment by RodrigoGutierrezTorres** [comment]
the same issue is observed in Windows 11

**Comment by ryokuu** [comment]
i am facing this bug too, the exit confirmation form keep appearing after pressing quit

**Comment by alsyundawy** [comment]
download from https://github.com/amanharwara/altus/actions still facing this bug too

**Comment by alsyundawy** [comment]
hi @amanharwara any update?

**Comment by amanharwara** [comment]
Pushed a fix, should be available in v5.0.1 :+1:

**Comment by amanharwara** [comment]
Also, the exit prompt can be disabled from the Settings
