### ISSUE TITLE
Blank screen after installation

### ISSUE THREAD

**Issue by konzertnr9** [amanharwara/altus#276]
**Describe the bug**
A blank screen is shown when running 5.0.0 after upgrading from 4.8.6

**To Reproduce**

1. Install 5.0.0 (upgrade from 4.8.6
2. Run

**Expected behavior**
Showing a screen with actual content

**Screenshots**
![image](https://github.com/amanharwara/altus/assets/7845520/15b88677-bda2-43c7-a07e-ae957c6df230)

**Information:**
Version Info (Go to About > About and click "Copy Version Info"): 5.0.0

**Comment by almar92** [comment]
Same problem in Ubuntu 22.04.03 with the AppImage version.

**Comment by almar92** [comment]
What solved it for me was downloading version 5.0.1 and re-adding the tab.

**Comment by amanharwara** [comment]
@konzertnr9 can you try upgrading to https://github.com/amanharwara/altus/releases/tag/5.0.2

**Comment by konzertnr9** [comment]
Yes it is fixed in 5.0.2
