### ISSUE TITLE
Zoom does not work

### ISSUE THREAD

**Issue by almar92** [amanharwara/altus#280]
Hello! Big fan of the Altus project. When using Altus 5.0.1 AppImage on Ubuntu 22.04.3 the client works and all but everything looks very tiny, and unlike with version 4.8.6 i can't zoom in or out with ctrl+ or ctrl-. Thank you in advance for your hard work!

The attached screenshot show how the client looks on a 1920x1080 resolution monitor. 

![Untitled](https://github.com/amanharwara/altus/assets/66468409/52caea69-053e-4071-a425-c8b70ed9852f)

**Comment by amanharwara** [comment]
Hi, thanks for reporting the issue! Fixed in [v5.0.2](https://github.com/amanharwara/altus/releases/tag/5.0.2)
