### ISSUE TITLE
Did the red dot disappear?

### ISSUE THREAD

**Issue by JoseHidalgo** [amanharwara/altus#287]
Hi,

I have updated Altus yesterday, from 4.8.6 to 5.0.2 (on Win 11 x64).
I haven't changed any settings.
Since the update, the red dot on the taskbar doesn't seem to appear anymore.
I'm talking about the red notification dot that signals a new incoming message.

I don't have any additional context and I don't think any screenshots are needed.
Feel free to let me know if you need any additional info.
Thanks in advance!

**Comment by JoseHidalgo** [comment]
Helloooooooooo! Hopefully my question won't go unnoticed. I'll keep asking.

**Comment by philipmgrant** [comment]
Sounds like you are also experiencing this: https://github.com/amanharwara/altus/issues/275

**Comment by amanharwara** [comment]
closing this since an issue for this already exists. see my comment here: https://github.com/amanharwara/altus/issues/275#issuecomment-2021497290

**Comment by amanharwara** [comment]
Reimplemented in https://github.com/amanharwara/altus/releases/tag/5.1.0 :+1:
