### ISSUE TITLE
Application damaged (MACOS)

### ISSUE THREAD

**Issue by riekadoo** [amanharwara/altus#290]
**Describe the bug**
A clear and concise description of what the bug is:
No matter the version, when I install the app on MacOS (M1 Macbook Air) and try to open it, I get the message that the app is damaged and I have to remove it. 

**To Reproduce**
Just download the app and copy to the application folder
Problem both with the ARM and the regular X64 version

**Expected behavior**
A clear and concise description of what you expected to happen:
Application opening

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Information:**
Version Info (Go to About > About and click "Copy Version Info"):
All versions

**Additional context**
None

**Comment by amanharwara** [comment]
https://github.com/amanharwara/altus/issues/260#issuecomment-1786099218

**Comment by riekadoo** [comment]
> [#260 (comment)](https://github.com/amanharwara/altus/issues/260#issuecomment-1786099218)

Fixed! Thank you (I added sudo, but that was all)
