### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by maxlieb** [amanharwara/altus#45]
Can an in application proxy support be added? 
I would very much like to see an option to configure the client to route all it's traffic (and only his traffic) through a proxy, specifically socks5 proxy in my use case.

This will be perfect for work, I'm a sysadmin, the network guys from my team block whatsapp media downloads, and though they have excluded our team, the exclusion rules are not always working... so I find it easier to just route whatsapp web traffic via shadowsocks + foxyproxy extension to my home network... then bugging the networking guys every time.

**Comment by ShadyThGod** [comment]
Can you provide some detail on how this should be implemented? I've never had to use proxies and such am not familiar with how to implement such a thing.
Would the option be a textbox where the user inputs something like `foobar:80`?

**Comment by amanharwara** [comment]
Closing since there hasn't been any response for more than a month.
