### ISSUE TITLE
Whatsapp update

### ISSUE THREAD

**Issue by eldar1971** [amanharwara/altus#46]
I'm using your product and came across something that I think is Bug,
The whatsapp constantly displays a message to update version. Everything I did, I couldn't keep up to date. The update only holds until the next time you open the program.

![whatsapp update](https://user-images.githubusercontent.com/61139337/74636538-e1850680-5170-11ea-87c9-ae1450f8aae7.png)

**Comment by amanharwara** [comment]
This is just annoying at best. If you click it, it doesn't actually do anything.
