### ISSUE TITLE
[Feature Request] Open File Instead Downloading Uploaded Files

### ISSUE THREAD

**Issue by Locked-Key** [amanharwara/altus#48]
Hi,

I would like to ask if files uploaded on a private message or group chat can be opened directly instead of requiring to be downloaded before you can open it.

Since Altus is using Electron, I presume you're using the WhatsApp Web. On the official WhatsApp web app, opening files directly aren't possible.

Looking forward to your feedback.

**Comment by amanharwara** [comment]
Since there are various file types, it would definitely not be feasible to hardcode functions for this. Although, I'll check the Electron docs if something like this is possible.
Can't guarantee anything yet.

**Comment by amanharwara** [comment]
I tried searching here and there, but I don't think it's really possible. There's no way to feasibly implement something like this, at least not yet.
