### ISSUE TITLE
Can't save settings on Linux

### ISSUE THREAD

**Issue by raulcraveiro** [amanharwara/altus#50]
I'm trying to change the settings, disabling the 3 options, but when I click save, It keeps loading forever and doesn't save anything.

I'm using the AppImage on Ubuntu 19.10.

**Comment by amanharwara** [comment]
Can you provide information on how you're running the AppImage?

**Comment by raulcraveiro** [comment]
I gave access to reading and writing and to execute as a software, and then open normally.

Is there anything specific that you need?

**Comment by amanharwara** [comment]
So I assume you ran something similar to this:
```
chmod a+x ./Altus.AppImage

./Altus.AppImage
```

**Comment by raulcraveiro** [comment]
I've tried this too and the settings still doesn't work :/

**Comment by amanharwara** [comment]
OK, I'll look into it.

**Comment by amanharwara** [comment]
Fixed in [v3.6.0](https://github.com/amanharwara/altus/releases/tag/3.6.0)

If you get an error on the start, delete `settings.json` file from data folder:

- `%appdata%/altus` on Windows
- `~/.config/altus` on Linux
- `~/Library/Application Support/altus` on macOS.
