### ISSUE TITLE
enhancement Extensions for the Chrome base

### ISSUE THREAD

**Issue by Mairex** [amanharwara/altus#51]
It would be awesome if we could use extensions within the Chrome base.

My goal would be the extension: https://chrome.google.com/webstore/detail/grammar-and-spell-checker/oldceeleldhonbafppcapldpdifcinji

Grammar and spell check ;)

**Comment by amanharwara** [comment]
Unfortunately because Electron (the API that Altus is based on) doesn't support extensions itself, there isn't any way for Altus to support them. Sorry.
