### ISSUE TITLE
...with Huawei P20Mate no sound... works with Samsung Galxy S4 mini...

### ISSUE THREAD

**Issue by Katermerlin** [amanharwara/altus#52]
Don't know whats up, but I noticed that there is no sound  (at videos) on Altus connected to Huawei P20 Mate... The connected Samsung Galxy S4 mini works fine.
If I download the respective .mp4 file to desktop, I can see the video and hear the sound playing it with vlc-player. So the mp4 seems to be OK...

Any Ideas?
Regards,
Wolfgang

**Comment by amanharwara** [comment]
Chances are that you have forgotten to turn on sound in the tab settings for the p20 mate.

It should look something like this:
![altus](https://user-images.githubusercontent.com/8348101/77733408-d43f1f80-702c-11ea-9fea-1d7129c19b54.gif)

**Comment by Katermerlin** [comment]
... That's it. I haven't noticed that.

Thank you very much....
Regares
Wolfgang
