### ISSUE TITLE
JavaScript Error in main process when launching Altus

### ISSUE THREAD

**Issue by Melvin-Abraham** [amanharwara/altus#53]
After updating Altus from `v2.3.3` to `v3.6.0`, I noticed that whenever I launch the application an exception is thrown in the start itself stating that an error occurred in the main process (`index.js`).

Below is the screenshot of the same:

![Screenshot (230)](https://user-images.githubusercontent.com/26056183/77817597-1a11eb80-70f2-11ea-859c-74fe245643e5.png)

```
TypeError: Cannot read property 'value' of undefined
```

**Comment by amanharwara** [comment]
Delete settings.json file from data folder:

- `%appdata%/altus` on Windows
- `~/.config/altus` on Linux
- `~/Library/Application Support/altus` on macOS.

**Comment by Melvin-Abraham** [comment]
Thanks. That worked for me... :)
