### ISSUE TITLE
Provide an option to close the app to tray

### ISSUE THREAD

**Issue by M3gaFr3ak** [amanharwara/altus#54]
An option to close to the tray item (minimize to tray instead of closing) would be awesome.

**Comment by amanharwara** [comment]
If you're on Windows or Mac, that option already exists.
On Linux, there's a bug which has lead me to get rid of it on Linux.

**Comment by M3gaFr3ak** [comment]
Did I miss something in the UI? I can minimize to tray, but Alt-F4 and the X-Button trigger the close dialog (or quit directly when disabling that).
What I mean is a close-to-tray similar to Skype and other such applications.
I've forked and modified (hardcoded) altus, demonstrating my intent, if you're interested :)

**Comment by amanharwara** [comment]
Oh you mean like when Alt+F4 or the X button is pressed, it should minimize to tray instead of closing?

**Comment by M3gaFr3ak** [comment]
Yeah exactly like that, I think it greatly increases efficiency for some people. It's quicker to just press alt-f4 or slide the mouse to the maximized windows x button (just the upper right corner, limited by screen edges) instead of searching for the minimize button.

**Comment by amanharwara** [comment]
Check out release [v3.9.0](https://github.com/amanharwara/altus/releases/tag/3.9.0).
