### ISSUE TITLE
No Notification

### ISSUE THREAD

**Issue by semisecco** [amanharwara/altus#56]
Hi,
first of all, I am just a user (from Germany) and really appreciate the job you've done with this app!
I use it for several days now and have the latest update but I never get a notification when I work e.g. in another programm (word, browser, whatever). 
Sound works (can I change the sound somewhere? And maybe even according to the respective account?).
Thanks

**Comment by amanharwara** [comment]
Are you sure notifications are turned on in the settings?

![altus](https://user-images.githubusercontent.com/8348101/77733408-d43f1f80-702c-11ea-9fea-1d7129c19b54.gif)

**Comment by semisecco** [comment]
Absolutely, I have both check boxes on active. I even tried the following: Disable (both), confirm, after reload enable both again... no changes.

**Comment by semisecco** [comment]
How are the notifications supposed to look like? Do they just pop up?

**Comment by amanharwara** [comment]
What operating system are you using? Also, what version of Altus are you using?

**Comment by semisecco** [comment]
Windows 10 Pro Version 1909 System Build 18363.720 
Altus Version 3.7.0

**Comment by amanharwara** [comment]
> How are the notifications supposed to look like? Do they just pop up?

They look like regular Windows 10 notifications, which come up at the bottom-right of the screen above the taskbar.

**Comment by semisecco** [comment]
Hmmm.... nope, nothing like that... But there isn't something I'd have to enable in windows? Just to be sure...

**Comment by amanharwara** [comment]
I think it's happening because of changes in WhatsApp itself. I'll issue a fix that will get the notifications working again.

**Comment by semisecco** [comment]
Great. And is there a chance to change the sound of the notification? I could not find it in any settings... Thanks again.

**Comment by amanharwara** [comment]
Unfortunately not. WhatsApp itself creates that sound, not Altus.

You can stop that sound if you want, by doing this:
![altus](https://user-images.githubusercontent.com/8348101/78658774-3da21680-78e8-11ea-962c-bae700c51873.gif)

**Comment by semisecco** [comment]
Ok... Well, maybe one day :-) It would be even greater to have different sounds for the different accounts :-) 

I really love the way you can show the "how to", I have never seen it this way before, great!

Thanks.... and if there is anything I could test for you, let me know (testing is part of my job...)

**Comment by amanharwara** [comment]
Should be fixed in [v3.8.0](https://github.com/amanharwara/altus/releases/tag/3.8.0).
Please update & let me know.

**Comment by semisecco** [comment]
Updated and yesssss :-) Got notifications, great job, thanks a lot!
