### ISSUE TITLE
Context menu text formatting

### ISSUE THREAD

**Issue by maicol07** [amanharwara/altus#57]
Add context menu entries for Bold, Italic, Monospaced and linestroked text

**Comment by amanharwara** [comment]
Can you tell me what symbols are used in WhatsApp for these?

**Comment by maicol07** [comment]
It's a modified markdown syntax. You can see them here: https://faq.whatsapp.com/en/android/26000002/

**Comment by maicol07** [comment]
If this can help, this extension adds these buttons to WA Web: https://chrome.google.com/webstore/detail/wabuddy/kpakemodngdilkffhnfofaggnfgclgao

**Comment by amanharwara** [comment]
I think I've finally managed to implement this. However, because WhatsApp uses a `contenteditable` div rather than a `textarea`, it's hard to set the position of the cursor. Due to this, when you format the text, the cursor jumps back to the start which is very annoying. I'll try to iron out this kink and then I'll release this as a feature.

**Comment by amanharwara** [comment]
Removing the `help wanted` label since I have achieved the main functionality for this.

**Comment by maicol07** [comment]
That's great!! Looking forward to the release

**Comment by amanharwara** [comment]
Implemented in [v3.13.0](https://github.com/amanharwara/altus/releases/tag/3.13.0).

Closing this issue. If you find any bugs related to it, please open a separate thread.

**Comment by maicol07** [comment]
@amanharwara where can I find the buttons bar? I can't find it...

![](https://user-images.githubusercontent.com/9463142/92112815-a1c0fc00-edee-11ea-8dd5-5555b6928753.png)

**Comment by amanharwara** [comment]
You have to enable "Utility Bar" in the tab settings.

**Comment by maicol07** [comment]
Ok, now works. Thank you!
