### ISSUE TITLE
I can't ear audio message in XUbuntu 18.04

### ISSUE THREAD

**Issue by mroubineau** [amanharwara/altus#58]
When i recive an audio message and i touch the play button, no sound anything, only the slider is moved, no more, no message error.

**Information:**
 - OS: XUbuntu 18.04
 - Altus Version 3.9.0

**Comment by amanharwara** [comment]
Make sure you've enabled sound like this:
![](https://user-images.githubusercontent.com/8348101/77733408-d43f1f80-702c-11ea-9fea-1d7129c19b54.gif)

**Comment by mroubineau** [comment]
is true... sorry, i never seem this option... tank you.This App is "The Solution". tank you again.

**Comment by mroubineau** [comment]
maybe, in the next version, you can put a small indicator icon in tab "sound null" for fools like me.

**Comment by mroubineau** [comment]
like chrome... 
![imagen](https://user-images.githubusercontent.com/64208102/80491623-59259d80-8939-11ea-96c5-e586bb97f084.png)

**Comment by amanharwara** [comment]
In the next version, I've made sound on by default. I realized that a lot of people didn't know that sound had to be turned on. So, I think it is better that sound is on by default.
