### ISSUE TITLE
Dark theme doesn't apply

### ISSUE THREAD

**Issue by davidrhoderick** [amanharwara/altus#60]
**Describe the bug**
Dark theme doesn't work

**To Reproduce**
Try to select the dark theme, even force refresh, shows light theme no matter what.

**Expected behavior**
That the dark theme would be applied

**Information:**
 - OS: Pop!_OS 20.04
 - Altus Version 3.7.

**Comment by amanharwara** [comment]
Update to [v3.8.0](https://github.com/amanharwara/altus/releases/tag/3.8.0)

**Comment by davidrhoderick** [comment]
So I tried that but now I can't update the settings and re-enable the Tab Bar, meaning I can't change the theme still...

**Comment by amanharwara** [comment]
What do you mean that you cannot update the settings?

**Comment by davidrhoderick** [comment]
So I updated the app, then I open the Settings dialog, enable the Tab Bar, then click save and it just spins I'll let it run for a while this time and see if anything happens.

**Comment by amanharwara** [comment]
Looks like saving might be broken for some reason. I'll look into it.

**Comment by davidrhoderick** [comment]
Thanks!

**Comment by amanharwara** [comment]
Can you see if it's fixed in [v3.9.0](https://github.com/amanharwara/altus/releases/tag/3.9.0)?

**Comment by amanharwara** [comment]
Or try [v3.10.0](https://github.com/amanharwara/altus/releases/tag/3.10.0). This is the latest version & everything should be working as intended I think.

**Comment by amanharwara** [comment]
Closing because of no reply.
