### ISSUE TITLE
Voice recordnings are not working

### ISSUE THREAD

**Issue by CollinAlpert** [amanharwara/altus#61]
**Describe the bug**
Currently I am not able to play voice recordning. The recording starts and the progress indicator moves, but there is no sound emitted.

**To Reproduce**
1. Open a chat.
2. Click on a voice recording
3. No output is emitted

**Expected behavior**
The sound is emitted through my speaker.

**Information:**
 - OS: Debian Buster
 - Altus Version 3.10

**Additional context**
I have Pulseaudio installed and am playing music through a web browser. So my output device is definitely set up correctly. Is there anything separate I need to configure or anything I could try?

**Comment by amanharwara** [comment]
Make sure sound is turned on like this:
![](https://user-images.githubusercontent.com/8348101/77733408-d43f1f80-702c-11ea-9fea-1d7129c19b54.gif)

If that doesn't work, try using [v3.10.0](https://github.com/amanharwara/altus/releases/tag/3.10.0)

**Comment by CollinAlpert** [comment]
Indeed, that was the problem. Why is sound not enabled by default?

**Comment by amanharwara** [comment]
Sound is enabled by default now in the latest version. I forgot to make it the default in previous versions.
