### ISSUE TITLE
Channel sidebar doesn't minimize anymore

### ISSUE THREAD

**Issue by randzone** [amanharwara/altus#62]
The whatsapp sidebar at the left with last used channels and conversations minimized to Icons size when the Altus window had a small width and you were writing

Now it stays wide, it only twitches shortly and jumps back to normal width.

Behaviour changed with 3.9 and is in 3.10 also.
New clean install happend to confirm.

**Comment by amanharwara** [comment]
I think this is intended behaviour in WhatsApp Web itself, because I don't personally remember making any changes like this.
