### ISSUE TITLE
chrome version

### ISSUE THREAD

**Issue by ssmns** [amanharwara/altus#63]
i see the message that:" whatsapp need to chrome 49+"

**Comment by amanharwara** [comment]
What version are you using?

**Comment by ssmns** [comment]
altus v3.10.0

**Comment by amanharwara** [comment]
Seems to be working fine for me.

If that error shows up, it reloads by itself. Are you letting it reload?

**Comment by ssmns** [comment]
Sometime a button for update chrome shows and after that this message display in altus.

**Comment by amanharwara** [comment]
That button actually does nothing. WhatsApp thinks it needs an update but it's already at the latest version. This is not an issue with Altus, but with WhatsApp itself. 

Just don't click the button. If you do and that error shows up, just press `Ctrl+Shift+R` to reload it and it will go away.
