### ISSUE TITLE
Aplicaton not starting.

### ISSUE THREAD

**Issue by Fokusnick** [amanharwara/altus#64]
**Describe the bug**
Aplicaton not starting.

**Screenshots**
![image](https://user-images.githubusercontent.com/66410667/83731170-bd333400-a652-11ea-8567-517f0a6cd33a.png)

**Information:**
 - OS: Windows 10
 - Altus Version [e.g. v3.11.0]

**Comment by amanharwara** [comment]
Looks like it didn't build correctly. I've updated the release.

Just re-download from [here](https://github.com/amanharwara/altus/releases/tag/3.11.0) and install. Should work.
