### ISSUE TITLE
Doesn't highlight incorrectly spelt words

### ISSUE THREAD

**Issue by MrMucho79** [amanharwara/altus#66]
The software doesn't highlight (red line under the word) words that have been spent incorrectly. 

**Information:**
 - OS: Windows 10
 - Altus Version 3.10.0

**Additional context**

**Comment by MrMucho79** [comment]
Hi, can i have an update regarding this please?

**Comment by amanharwara** [comment]
Changes to the code have been made. I'm having trouble building it however, so the release is a bit delayed.

**Comment by MrMucho79** [comment]
Thanks, can you tell me once its completed please?

**Comment by amanharwara** [comment]
Check out release [v3.12.0](https://github.com/amanharwara/altus/releases/tag/3.12.0) and let me know.

**Comment by MrMucho79** [comment]
Thank you, this is good.

 

Any chance when you click on the word that spelt wrong to give you the correct spelling?

 

Thanks

 

Mel

**Comment by amanharwara** [comment]
> Any chance when you click on the word that spelt wrong to give you the correct spelling?

Right-clicking the word may give you the options but I'm not sure. And I don't intend to implement it myself either.
