### ISSUE TITLE
Downloading of files

### ISSUE THREAD

**Issue by MrMucho79** [amanharwara/altus#67]
**Describe the bug**

When i download any type of file it doesn't download the file format, why?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information:**
 - OS: [e.g. Windows] - Windows 10
 - Altus Version [e.g. v3.5.0] - Version v3.10.0

**Additional context**

**Comment by amanharwara** [comment]
Can you explain in detail? Because downloads are working fine for me.

**Comment by MrMucho79** [comment]
Hi

The file type works now but this always pops up.

**Comment by MrMucho79** [comment]
Hi

 

This is what happens sometimes when I download files.

**Comment by amanharwara** [comment]
Check out release [v3.12.0](https://github.com/amanharwara/altus/releases/tag/3.12.0) and let me know.

**Comment by MrMucho79** [comment]
Thanks, I will test and let you know.
