### ISSUE TITLE
Cannot use in two pcs simultaneously ?

### ISSUE THREAD

**Issue by sostenesapollo** [amanharwara/altus#68]
![image](https://user-images.githubusercontent.com/35838667/84397617-38599480-abd5-11ea-9e96-adbb3f23325a.png)

How to use, or enable this function ?

**Comment by amanharwara** [comment]
Not a bug. It is intentional in WhatsApp itself, not under my control.

**Comment by sostenesapollo** [comment]
Yes, of course its not a bug, bug have any way to do this ?

**Comment by amanharwara** [comment]
It could possibly be done by manipulating cookies but I personally don't know how to and I also don't think it would be secure to do so.

**Comment by sostenesapollo** [comment]
Ok, cookies... thats make some sense, but I will look for something about it. Thanks...
