### ISSUE TITLE
I want to use altus with one proxy connection per account (socks5 or http proxy)

### ISSUE THREAD

**Issue by jnntin** [amanharwara/altus#69]
I want to use altus with one proxy connection per account (socks5 or http proxy), can you help me achieve this?

**Comment by amanharwara** [comment]
Yes, I was previously asked to implement this as well, but they didn't reply back when I asked them about the implementation.

So, as I understand it, you would want to use a proxy rule string (for e.g. `http=foopy,socks5://bar.com`) to apply it to a tab right?

**Comment by jnntin** [comment]
How do I contact you and I can pay some fee to implement this feature.

Do you have a whatsapp?

**Comment by amanharwara** [comment]
You can e-mail me at `amanharwara@protonmail.com` or message me on Discord ([Here](https://discord.gg/mGxNGP6) is the link to the Discord channel for this app. You can find me as `shadythgod#6956` there).

**Comment by amanharwara** [comment]
I'd recommend using a platform like [IssueHunt](https://issuehunt.io/) or [BountySource](https://bountysource.com/) if you want to pay someone to get this implemented. I'd be willing to accept PRs. But it's not something I'm going to implement at the moment.
