### ISSUE TITLE
Unable to start on macOS 10.14.6

### ISSUE THREAD

**Issue by iamcaner** [amanharwara/altus#71]
**Describe the bug**

Application doesn't start on macOS 10.14.6

**To Reproduce**

Download the application, drag to Applications folder, try to open.

**Expected behavior**

Application should start.

**Screenshots**

![image](https://user-images.githubusercontent.com/936167/86887614-7f1daa00-c101-11ea-9ab6-837887c00e33.png)

**Information:**
 - OS: macOS 10.14.6
 - Altus Version: 3.12.0

**Comment by amanharwara** [comment]
Is this a fresh install or did you have this problem after an update?

**Comment by MWenius** [comment]
Same problem after a fresh install.
System: MacOS Catalina, Version 10.15.5
Altus Version: 3.12.0

**Comment by iamcaner** [comment]
Hi @amanharwara that was my first attempt the use this application. Tried the previous version after seeing this error, it seems working on that version, it looks like something on the latest v3.12 release broke the Mac version.

**Comment by amanharwara** [comment]
Please test out [v3.2.1](https://github.com/amanharwara/altus/releases/tag/3.12.1) and let me know :)

**Comment by mwerder** [comment]
good job, it works for me 👏

**Comment by iamcaner** [comment]
I can confirm that latest version is working now.
