### ISSUE TITLE
Altus starts with "Default Theme" even with "Dark Theme" set

### ISSUE THREAD

**Issue by Melvin-Abraham** [amanharwara/altus#74]
### Description
I recently updated to Altus `v3.12.1` and noticed that even with my theme set to **Dark**, Altus starts with **Default** theme even when forcing a reload.

Currently in order to get back to dark theme, I am setting the theme to Default (then save) and then set the theme back to Dark (then save).

### To Reproduce
1. Start/Force Reload _Altus_ (make sure you have theme set to `Dark`)
2. **Default theme** shows up instead of **Dark theme**

### Expected behavior
Altus should have started with Dark theme

### Screenshots
![image](https://user-images.githubusercontent.com/26056183/88360833-ad071d80-cd94-11ea-82dc-a17a4f1fe301.png)

### Information:
 - **OS:** Windows 10 2004 _(Build 19041.388)_
 - **Altus Version:** v3.12.1

**Comment by amanharwara** [comment]
Hmm looks like WhatsApp might've change how the dark theme is enabled.

For now, you can go to the WhatsApp settings > Theme > Choose "Dark". This is in the WhatsApp settings, not Altus.

**Comment by Melvin-Abraham** [comment]
@amanharwara Thanks that works for the time-being. :)

**Comment by amanharwara** [comment]
Found a fix for this. Will be available in next release.

**Comment by amanharwara** [comment]
[v3.13.0](https://github.com/amanharwara/altus/releases/tag/3.13.0)

**Comment by Melvin-Abraham** [comment]
The issue seems to be resolved in `v3.13.0`. Closing this issue...
