### ISSUE TITLE
"Return" sends message immediately without warning

### ISSUE THREAD

**Issue by Katermerlin** [amanharwara/altus#75]
There should be a switch for prevention of sending if the "Return" key is hit, like in the Android version of Whatsapp. It happens often that Return is hit by mistake and the message is sent. The Return should work only for vertical spacing, sending only by activating the "Send" - arrow...

**Comment by amanharwara** [comment]
So far from what I've tried to implement this, none of it seems to work. This is mainly because of how the message box seems to work.

I'm not sure if I can implement this but PRs are welcome.

**Comment by Katermerlin** [comment]
I'm not sure what "PR" is...
Nevertheless, IMHO it should be possible to "catch" the Enter-command before it is sent to the system... I think the "Enter" is the same as the CRLF, isnt'it? 
It's because I was told that any command sent by the keyboard can be catched before execution resp. execution can be prevented... Maybe this hint helps...

**Comment by amanharwara** [comment]
Will release a new version with this feature in a day or so.

**Comment by amanharwara** [comment]
@Katermerlin this feature has now been implemented in [v3.16.0](https://github.com/amanharwara/altus/releases/tag/3.16.0). Please try it out. You will need to turn it on in the settings first.
