### ISSUE TITLE
Clicking the notification does nothing on Windows 10

### ISSUE THREAD

**Issue by JosephTico** [amanharwara/altus#76]
**Describe the bug**
Using the latest version available in releases, when a notification arrives for a chat nothing happens when you click it.

**To Reproduce**
1. Enable notifications
2. Minimize the program
3. When a notification arrives, click it

**Expected behavior**
Altus should open the corresponding chat.

**Information:**
 - OS: Windows 10
 - Altus Version: 3.12.1

**Comment by amanharwara** [comment]
Sorry for the very late reply. My main Windows 10 machine doesn't have notifications and my Windows 10 VM was not working until today.
I tested this on it and it seems to work as intended; the corresponding chat opens up. 

I think you might be referring to the fact that clicking the notification doesn't maximize the window. If you are referring to that, unfortunately I can't do much about that. For that, I would have to implement a custom notification object but it becomes very hard to maintain.

**Comment by amanharwara** [comment]
Closing due to no response.
