### ISSUE TITLE
FR: Provide a zsync update file for AppImages

### ISSUE THREAD

**Issue by srevinsaju** [amanharwara/altus#79]
AppImages support delta updates. That means, a user would no longer have to download the 70 MB again on every update.
To create a zsync file
```bash
./Altus*.AppImage --appimage-extract
./appimagetool*.AppImage -u 'gh-releases-zsync|amanharwara|altus|continuous|Altus*.AppImage.zsync
```

If you prefer, I can create an automatically publishing CI on github actions, which does the thing

**Comment by amanharwara** [comment]
This looks interesting. Can you tell me what the experience would like for the end-user? 
I mean I'll have to publish the whole release anyway, so how will the user download only the necessary parts?

**Comment by srevinsaju** [comment]
Glad to explain.

When you create an AppImage using `-u` flag, i.e to provide the updateinformation is embedded within the appimage, the AppImage can be updated either with
* a tool, called **AppImageUpdate**
* an appimage package manager, for example **Zap**

the -u flag triggers appimage tool to provide a Zsync file. A zsync file looks like [this](https://github.com/srevinsaju/element-appimage/releases/download/stable/Element-v1.7.4-GLIBC-2.17.AppImage.zsync). The zsync file, (sample) is of Element / Riot Chat client. 

When appimageupdate or zap is run, it queries the updateinformation within the appimage, when that happens, the output will be like
`gh-releases-zsync|amanharwara|altus|continuous|Altus*.AppImage.zsync`

Now, this is translated to 
`https://github.com/amanharwara/altus/releases/tag/continuous/Altus*.AppImage.zsync`

and that file is downloaded. The zsync file contains hashes of each block. 
The updater compares each block of the AppImage with the zsync file to see if it matches, if it does not, that particular block is downloaded using request apis to set the get location, similar to how the Linux `wget` can continue an aborted download using `-c` parameter. 

The downloaded file is recompiled to a perfect and updated appimage.

Now all these are made easy, using a tool like AppImageUpdate,
for example:
```
./appimageupdate*.AppImage Altus*.AppImage
``` 
will update the Altus AppImage

or more preferably, simply
```bash
zap install altus
zap update altus
```
