### ISSUE TITLE
No notification count on tray icon

### ISSUE THREAD

**Issue by maicol07** [amanharwara/altus#81]
**Describe the bug**
The tray icon does not show any notification counter, while in the apps bar it does

**To Reproduce**
1. Minimize to tray Altus
2. Get a message
3. Tray doesn't have notification count
You can try the same with the app minimized in the apps bar and see that works in this way

**Expected behavior**
Notification counter

**Screenshots**
Tray: 
![immagine](https://user-images.githubusercontent.com/9463142/92113328-71c62880-edef-11ea-9fdb-742c47f3503d.png)

**Information:**
 - OS: Windows 10 
 - Altus Version 3.14.0

**Comment by maicol07** [comment]
It seems that this doesn't work all the times...

**Comment by amanharwara** [comment]
Oh I forgot to account for when the app is minimized to tray, so I never implemented the notification count for the tray icon. I'll try and get it working.

**Comment by amanharwara** [comment]
> @amanharwara it seems that also in the apps bar doesn't work...

Just tried it on my system and it works correctly there.

**Comment by maicol07** [comment]
> Just tried it on my system and it works correctly there.

Mine not...

**Comment by maicol07** [comment]
Now works with 3.15! Closing this
