### ISSUE TITLE
Hidden first mention when using utility bar

### ISSUE THREAD

**Issue by maicol07** [amanharwara/altus#82]
**Describe the bug**
First contact to mention is hidden (by the utility bar, see screenshot)

**To Reproduce**
1. Go to a group chat
2. Type `@`
3. You can see the first result is hidden by the utility bar

**Expected behavior**
Contacts moved above the bar

**Screenshots**
With utility bar:
![immagine](https://user-images.githubusercontent.com/9463142/92898255-1fec5680-f41e-11ea-816d-8c85fea89c3c.png)

Without:
![immagine](https://user-images.githubusercontent.com/9463142/92898541-588c3000-f41e-11ea-9531-b6ea40327f0c.png)

**Information:**
 - OS: Windows 10
 - Altus Version 3.14

**Comment by amanharwara** [comment]
@maicol07 Can you confirm if this is fixed in 3.15.0?

**Comment by maicol07** [comment]
Fixed! Thank you!
