### ISSUE TITLE
Java Script Error 

### ISSUE THREAD

**Issue by Allespat** [amanharwara/altus#86]
An error window pops up every few seconds:

A JavaScript error occurred in the main process

Uncaught Exception:
TypError: Cannon read property 'setImage' of undefined.
at IpcMainImpl.<anonymous>
(C:\Users\user\AppData\Local\Programs\Altus\resources\app.asar\index.js:915:22)
at IpcMainImpl.emit (events.js:223:5)
at WebContents.<anonymous> (electron/js2c/browser_init.js:173:8161)
at WebContents.emit (events.js:223:5)

**Comment by amanharwara** [comment]
Thanks for reporting. I've fixed it and will release an update soon.

**Comment by amanharwara** [comment]
Release [v3.15.1](https://github.com/amanharwara/altus/releases/3.15.1) should fix this.
