### ISSUE TITLE
Version 3.15.1 don't work on Win10 (32), doesn' connect to Smartphone

### ISSUE THREAD

**Issue by Katermerlin** [amanharwara/altus#90]
Version 3.15.1 don't work on Win10 (32), doesn't connect to Smartphone. After reinstalling Version 3.14 everything seems to be OK again...

**Comment by amanharwara** [comment]
Can you describe it in more detail?

**Comment by Katermerlin** [comment]
After staring Altus, it tries to connect to the smartphone, but it doesn't. I see just a light grey screen in Altus without information...

**Comment by amanharwara** [comment]
Going back to v3.14 fixed it for you?

**Comment by amanharwara** [comment]
I'm asking because there hasn't really been that many changes between 3.14 and 3.15 that might stop this from working.

Can you try uninstalling it completely and then re-installing?

**Comment by Katermerlin** [comment]
I uninstalled it with the provided uninstall-command before reinstalling 3.14 and 3.15.
But after that I found that only 3.14 works here...
What do you mean with "completely"?
Attached the system-Info (Win10 32Bit).

![MeinBild2](https://user-images.githubusercontent.com/34886288/94342340-b91b8f80-0010-11eb-907e-0d151893d42a.jpg)

**Comment by amanharwara** [comment]
> What do you mean with "completely"?

The uninstaller only removes the main program files, not the data files (usually). This is so the user doesn't have to set it up again when they re-install.

So what you can try to do is go in the File Explorer, then in the location bar type `%appdata%` and press Enter. Then look for a folder called `altus` and delete it. Then install 3.15 again.

**Comment by Katermerlin** [comment]
...After total uninstall of Altus and reinstall Version 3.15.1 works now...
Thanks for your Help
