### ISSUE TITLE
No utility bar when replying

### ISSUE THREAD

**Issue by maicol07** [amanharwara/altus#94]
**Describe the bug**
When replying a message, utility bar is hidden until the message is sent or the reply canceled (and returns a normal message in this last case)

**To Reproduce**
1. Reply to a message
2. Utility bar is hidden until you send the message or cancel the reply

**Expected behavior**
Utility bar should be visible when replying to messages

**Information:**
 - OS: Windows 10
 - Altus Version 3.15.1

**Comment by maicol07** [comment]
With v3.20.1, the reply preview is hidden, while the utility bar is visible. Maybe related to #103?

**Comment by amanharwara** [comment]
I've found a fix for both. Will be in the next release.

**Comment by amanharwara** [comment]
[v3.21.0](https://github.com/amanharwara/altus/releases/tag/3.21.0) should fix this.

**Comment by maicol07** [comment]
Ok, this is fixed, although it's a bit unresponsive when the utility bar moves up and down...

**Comment by amanharwara** [comment]
Yes, I'm aware. It's because for some reason, unless I wait for a second before moving it, it doesn't correctly get the height of the reply. I'm not really sure what could be done to make it instantaneous.

**Comment by amanharwara** [comment]
Closing as this should be fixed.
