### ISSUE TITLE
Add option to remove utility bar

### ISSUE THREAD

**Issue by reg31** [amanharwara/altus#98]
The bar takes space on small screens and is not always used.

**Comment by amanharwara** [comment]
The option's already there. You can go to the tab's settings and turn it off.

**Comment by reg31** [comment]
What is the label of this option? I do not see any mention to the utility bar in the settings.

**Comment by amanharwara** [comment]
![2020-10-07 19_50_12-Window](https://user-images.githubusercontent.com/8348101/95343818-7b3c2800-08a8-11eb-90f1-49cb8af0255b.png)

This option shows when you first create a tab as well.

**Comment by reg31** [comment]
Cool, I was looking for it in settings though it was in tab preferences.
