### ISSUE TITLE
Taskbar transparency

### ISSUE THREAD

**Issue by reg31** [amanharwara/altus#99]
A nice enhancement is to have a transparent titlebar.

**Comment by amanharwara** [comment]
Can you elaborate please? What do you mean by transparent taskbar?

**Comment by reg31** [comment]
I mean titlebar not taskbar sorry.

**Comment by amanharwara** [comment]
Is there any other app that does this? Because I don't see what the use case for implementing this... What benefit would this give?

**Comment by reg31** [comment]
This can be closed, the custom theme defeats the purpose. Good job by the way.
